### ISSUE TITLE
GitHub usernames

### ISSUE THREAD

**Issue by nvbach91** [nvbach91/4IZ268-2020-2021-ZS#1]
Toto vlákno slouží k sesbírání GitHub username studentů.

Do komentáře napište pozdrav s vaším jménem, xname (InSIS login) a GitHub username. A buďte kreativní!

Díky

P.S.: Pokud nechcete být zaspamovaný, klikněte na Unsubscribe vpravo
![image](https://user-images.githubusercontent.com/20724910/94841843-e0140000-041a-11eb-9a1b-39ef6016dd8b.png)

**Comment by kakashi91** [comment]
Ahoj mistře Yodo! Jmenuji se Alžběta Počítačová. Můj xname je **`poca01`** a můj GitHub username je **`blabla`**. 

S pozdravem.
![image](https://user-images.githubusercontent.com/20724910/94747563-80b4e200-037f-11eb-8679-58d61f75126a.png)

**Comment by hawrancz99** [comment]
Zdravím,
Moje jméno je Lukáš Vávra, můj xname je **`vavl03`** a GitHub username je **`hawrancz99`**.
![github meme](https://i.imgur.com/Ry64wWc.jpeg)

**Comment by Zofak** [comment]
Hello there, 

Jsem tu. Zof
xname: zofm00
GHusername: Zofak

**Comment by BlazeCZ** [comment]
Dobrý den,
Mé jméno zní **Jiří Šindela**, xname **_sinj04_** a GitHub username  **_BlazeCZ_**.

**Comment by valm08** [comment]
Doporučenými názvy se moc neřídím, tak username je login (valm08).

Jmenuji se Miroslav Valášek.

PS: vybral jsem si jiný SFTP klient, jelikož WinSCP je aplikace pro Windows.

**Comment by jedv00** [comment]
Václav Jedlička se hlásí do služby pod GitHub username **jedv00** (nečekaně mám i stejný xname)

### **S piví jde samozřejmě všechno líp**
![Pozvi 4FISáka na piví](https://user-images.githubusercontent.com/72194501/94792821-d1592900-03d9-11eb-808b-44b2e0bed100.jpg)

**Comment by toho00** [comment]
Dobrý den,
Můj xname je toho00 a můj GitHub username je toho00

**Comment by ladahorky** [comment]
Zdravím, xname je `horl13` a GitHub username je `ladahorky`.

**Comment by lukyPinky** [comment]
Dobrý den, 
jmenuji se Lukáš Pinkas. Můj xname je **pinl01** a GitHub username je **lukyPinky**.

**Comment by dinv00** [comment]
Dobrý den, 
jsem Dinh Van Chien, muj xname a Github username je **dinv00**.
![stark](https://user-images.githubusercontent.com/58660534/94818864-de3c4380-03fe-11eb-9e78-a494b3630e80.gif)

**Comment by dzidon** [comment]
Zdravím,
jmenuji se David Židoň. Xname: **zidd00**, GitHub username:  **dzidon**

**Comment by vetrovskyj** [comment]
Dobrý den,
moje jméno je Jan Větrovský, xname je **vetj00** a GitHub username **vetrovskyj**

**Comment by kyvt** [comment]
Dobrý den,
jmenuji se 𝓣𝓮𝓻𝓮𝔃𝓪 𝓚𝔂́𝓿𝓪𝓵𝓸𝓿𝓪́, můj xname je 𝕜𝕪𝕧𝕥𝟘𝟘 a GitHub username 🅚🅨🅥🅣.

**Comment by anetapls** [comment]
Zdravím,

Jsem Aneta Štěpánková, dle xname `stea11` a GitHub username budiž `anetapls`, protože už nevím, sorry 🙃 
![obrazek](https://user-images.githubusercontent.com/72199532/94832376-1eef8900-040e-11eb-88be-7c97ff78a34a.png)

**Comment by l-k-sfr-jt** [comment]
git: 👆
Jmenuji se _Lukáš Frajt_ a muj xname je `fral06`

**Comment by bnaru** [comment]
Dobrý den, 
jmenuji se Barbora Nováková, můj xname je **novb12** a GitHub username **bnaru**.

**Comment by Bejt02** [comment]
Dobrý den,
jmenuji se Tereza Bejšovcová a můj xnam je bejt02 a GitHub unsername také bejt02.

**Comment by UnrealNeriel** [comment]
Shinzou wo Sasageyo, jmenuji se Pavlo Prykhnenko, můj xname je **pryp00** a GitHub username je **UnrealNeriel**.

**Comment by apatenko369** [comment]
Dobrý den,
jmenuji se Ivan Apatenko, xname: apai00, GitHub username: apatenko369

**Comment by petr-klepetko** [comment]
Dobrý den, 
Jmenuji se Petr Klepetko, můj xname je klep03, github username mám petr-klepetko.

Mám mac, takže musím najít alternativu pro WinSCP, ale ještě ji nemám, protože nejsem tak chytrý, jako Miroslav Valášek a vše nechávám na poslední chvíli. Takže bojuji za to, abych nemusel zase vytahovat ze skříně starý win notebook a místo práce na cviku čekat, než se mi zapne počítač 😶

**Comment by jpodestat** [comment]
Dobrý den,
Jmenuji se Jan Podestát, můj xname je podj00 a na githubu mám username jpodestat.

**Comment by andreaborekova** [comment]
Dobrý deň, 
Volám sa _Andrea Boreková_, môj xname je **bora13** a môj GitHub username je **andreaborekova**

**Comment by steepp** [comment]
Hello,
name is Yaroslav Stepchyn
insis: stey04
GitHub: steepp

**Comment by voiran** [comment]
Zdravím,
jmenuji se Pavel Seidl, xname: **seip00**, GitHub username **voiran**

![66x7unqp3cp51](https://user-images.githubusercontent.com/55685555/94858835-ecf11d80-0433-11eb-8993-6d8879021049.jpg)

**Comment by SDostalkova** [comment]
Štěpánka Dostálková aka doss02(insis) aka SDostalkova(GitHub) je na palubě kapitáne! 
Vyrážíme na širé moře... ! Prosím pomalu... mám mořskou nemoc...

**Comment by dmitrijt9** [comment]
Hello world,
jsem Dmitrij Tkačenko.

- insis: tkad06
- github: dmitrijt9

**Comment by goonerknight** [comment]
Zdravíčko,

jméno: Michael Rytíř
insis: rytm02
github: goonerknight

Těší mě

**Comment by ngut37** [comment]
Zdravím všeci, 👋 
Jmenuji se Nguyen Trung Thu a rád píšu gorilla-code. 🦍 
```
xname = 'ngut37'
githubUsername = xname
```

> "To infinity...and beyond!" 🚀

**Comment by kasm13** [comment]
Dobrý den. Jmenuji se Martin Kasan, můj xname je **`kasm13`** a github username je **`kasm13`**.

**Comment by TimoGeist** [comment]
Dobrý den,
jmenuji se **Martin Timoščuk** a můj xname je **timm02**.
Snad tu nejsem jediný, koho vystihuje následující obrázek.
![120344769_636890710356825_174969877178812616_n](https://user-images.githubusercontent.com/71336686/94892442-eb9c1100-0484-11eb-8a1a-0bd52ac9a087.jpg)

**Comment by kyvt** [comment]
Dobrý den,
jmenuji se **_Tereza Kývalová_**, můj xname je _**kyvt00**_ a GitHub username je _**kyvt**_.

**Comment by vojtar** [comment]
Hi!
name: Vojtěch Růžička
github: vojtar
xname: ruzv01

**Comment by NikolPP** [comment]
Dobré ránko, real jméno je Nikola Pospíšilová, xname - posn01, github přezdívka NikolPP.

**Comment by dnovosad1** [comment]
Dobrý den,
jmenuji se Dominik Novosad.
xname: novd35
github: dnovosad1

**Comment by beld06** [comment]
Dobrý den,
jmenuji se Daria Beliavskaia.
xname: beld06
github: beld06

**Comment by ghost** [comment]
Dobrý den
moje jméno je Tomáš Pivný
xname: pivt02
github: tompivny

**Comment by rasulyao** [comment]
Dobrý den
Jmeno: Rasul Ayupov
Xname: ayur00
github: rasulyao

**Comment by ulvo00** [comment]
Zdravím,
Moje jméno je Ondřej Ulvr, GitHub username mám stejný jako xname, tedy **ulvo00**.

**Comment by david-prochazka** [comment]
```
<!DOCTYPE html>
<html>
  <head>
    <title>David Procházka</title>
  </head>
  <body>
    <h1>Helou</h1>
    <p>Já jsem David Procházka s velmi kreativním GitHub username david-prochazka a můj xname je prod10.</p>
  </body>
<html>
```

**Comment by sikj01** [comment]
10 minut jsem zjišťoval, jak komentovat a až pak zjistil, že musím prvně verifikovat mail. Vysálo to celou mojí nádrž dnešní kreativnosti.
Jan Sikora, username stejný jako xname, tedy Sikj01

**Comment by jedv00** [comment]
> 10 minut jsem zjišťoval, jak komentovat a až pak zjistil, že musím prvně verifikovat mail. Vysálo to celou mojí nádrž dnešní kreativnosti.
> Jan Sikora, username stejný jako xname, tedy Sikj01

Pěkně Honzo :D

**Comment by sikj01** [comment]
nech mě vole
________________________________
Od: jedv00 <notifications@github.com>
Odesláno: pátek 2. října 2020 10:36
Komu: nvbach91/4IZ268-2020-2021-ZS <4IZ268-2020-2021-ZS@noreply.github.com>
Kopie: Jan Sikora <sikj01@vse.cz>; Comment <comment@noreply.github.com>
Předmět: Re: [nvbach91/4IZ268-2020-2021-ZS] GitHub usernames (#1)


10 minut jsem zjišťoval, jak komentovat a až pak zjistil, že musím prvně verifikovat mail. Vysálo to celou mojí nádrž dnešní kreativnosti.
Jan Sikora, username stejný jako xname, tedy Sikj01

Pěkně Honzo :D

**Comment by kokomoloko** [comment]
Dobrý den,
jmenuji se Maryia Tomchanka 
xname: tomm08
github: kokomoloko

**Comment by madkhab** [comment]
Ahoooj,
my name ===Madi Khabidenov, 
xname ===kham06,
github ===madkhab,
The end.

**Comment by Duzij** [comment]
zDRAVÍM,

- name: Maxim Dužij
- xname: duzm00
- github: duzij

**Comment by ivajlovska** [comment]
Ahojte :)

Jmenuje se Alisa Ivailovskaia, můj xname = ivaa07, na githubu aka ivajlovska

**Comment by petrpotmesil** [comment]
Dobrý den, 

Jmenuji se Petr Potměšil
xname: popt04
github: petrpotmesil

**Comment by nvbach91** [comment]
Všichni padawanové kteří se stihli zaregistrovat na GitHub mají 1 bod za aktivitu.

Připomínám, že registrace na GitHub je povinná a bez toho se neobejdete.

**Comment by nvbach91** [comment]
Všem jsem poslal pozvánku pro přístup do našeho repozitáře, tak nezapomeňte ji akceptovat.

**Comment by pfej00** [comment]
Dobrý den

- Jan Pfeiffer, pfej00, pfej00@vse.cz

**Comment by Pulman3** [comment]
Ahoj,
jmenuji se Václav Géryk , můj xname je gerv03 a GitHub username je Pulman3

**Comment by nvbach91** [comment]
![image](https://user-images.githubusercontent.com/20724910/95195233-8e7ec300-07d6-11eb-9219-e3d1a839c7a8.png)

**Comment by nik1488** [comment]
Bonsoir,

jmenuji se Nikita Privalikhin, xname je **prin03**, Github: **nik1488**

**Comment by Foky09** [comment]
Zdravím,

Jmenuji se František Fousek, xname **fouf00** , Github **Foky09**

**Comment by alexmalychu** [comment]
Dobrý den. Jmenuji se Alex Malychů, můj xname je mala12 a username alexmalychu.

**Comment by oli711** [comment]
Dobrý den,
Jmenuji se Olesia Kozlova.
Můj xname je kozo01 a můj GitHub username je oli711.

**Comment by michalmrkus** [comment]
Dobrý večer,
Jméno: Michal Mrkus, 
xname: mrkm00,
GitHub username: michalmrkus

**Comment by VividBoop** [comment]
Jméno: Luboš Pata,
xname: patl03,
GitHub username: VividBoop

**Comment by tmikula-dev** [comment]
Dobrý den,
moje jméno je Tobiáš Mikula,
xname je mikt05 a GitHub username je MobiTikula.
Hezkej den🤗

**Comment by AndriiTuma** [comment]
Dobrý den.
moje jméno je Andrii Tuma,
xname je tuma02 a GitHub username je AndriiTuma.
Hezkej den

**Comment by nvbach91** [comment]
@alexmalychu
@david-prochazka
@Duzij
@goonerknight
@hawrancz99
@kasm13
@kyvt
@l-k-sfr-jt
@madkhab
@NikolPP
@petr-klepetko
@petrpotmesil
@rasulyao
@sikj01
@vetrovskyj
@vojtar
@Zofak

 Co nejdříve prosím odklikněte pozvánku do repozitáře:
https://github.com/nvbach91/4IZ268-2020-2021-ZS/invitations 

Díky

**Comment by evgeniyMtl** [comment]
name: Yevhen Udpvychenko
username: EvgeniyUdovichenko
xname: udoy00

**Comment by vittalyya** [comment]
name: Viktoriya Lozyan
username: vittalyya
xname: lozv00

**Comment by vecs00** [comment]
Šárka Večerníková, vecs00
