### ISSUE TITLE
SP2 návrh - otázka

### ISSUE THREAD

**Issue by pfej00** [nvbach91/4IZ268-2020-2021-ZS#107]
Dobrý den,

Chtěl bych se zeptat jestli v druhé semestrální práci musíme v AJAXu využít všechny metody GET, POST, PUT, DELETE, protože mám v plánu udělat burzovní aplikaci,
která bude načítat ceny akcií a kryptoměn a v ní tyto ceny zpracuju do grafů podle datumu a času. Dále by tam byly aktuální finanční zprávy a další žebříčky a k tomu využiju nejspíš jenom GET.
Dále mám otázku na formulář pro téma, kde je pole pro knihovny nebo zdrojové kódy, může to platit prozatím jenom pro framework nebo jquery? Ptám se z toho důvodu, že bych potom mohl
dodatečně využít nějakou speciální knihovnu, která ale nebude v návrhu.

S pozdravem
Jan Pfeiffer, pfej00

**Comment by nvbach91** [comment]
Stačí aby tam bylo vidět, že umíte pracovat s Promise nebo async, takže na těch metodách nezáleží, ale nice to have jsou GET a POST.

Počet knihoven by měl být 2 a více, takže tam pak lze dodatečně přidat dle domluvy.

**Comment by pfej00** [comment]
Děkuju za odpověď.
