### ISSUE TITLE
vavl03-sp1

### ISSUE THREAD

**Issue by hawrancz99** [nvbach91/4IZ268-2020-2021-ZS#108]
Oprava:
https://eso.vse.cz/~vavl03/sp1/
https://eso.vse.cz/~vavl03/sp1/about/
https://eso.vse.cz/~vavl03/sp1/reference/
https://eso.vse.cz/~vavl03/sp1/faq/
https://eso.vse.cz/~vavl03/sp1/contact/
https://eso.vse.cz/~vavl03/sp1/postmail/succes.html
https://eso.vse.cz/~vavl03/sp1/postmail/error.html
https://eso.vse.cz/~vavl03/sp1/assets/styles/styles.css

Pozadí na verzi pro tisk bylo schováno už v předchozí verzi, tudíž moc nerozumím vaší poznámce "na verzi pro tisk schovejte to pozadi". Jinak by mělo být vše opraveno. Děkuji.

**Comment by nvbach91** [comment]
Já pořád vidím to pozadí btw: zkuste tam někam připsat !important
![image](https://user-images.githubusercontent.com/20724910/100785561-1c5edf00-3411-11eb-8f8c-1aacb1c62878.png)

**Comment by hawrancz99** [comment]
Přidal jsem tam !important, snad už pozadí zmizí i vám. Já ho tam opravdu nemám: 

![Imgur](https://i.imgur.com/9EPicbr.png)

Napadá mě jen jestli by nepomohlo vymazat mezipamět v prohlížeči.

**Comment by nvbach91** [comment]
nn, to je tim ze mam zaply background graphics a Vy asi ne, a to !important ma byt u background image a ne background color...
![image](https://user-images.githubusercontent.com/20724910/100787396-dd7e5880-3413-11eb-9afc-597fc7617e47.png)

**Comment by hawrancz99** [comment]
Aha, tak jsem tam přidal ještě ten background-image. Neměl jsem zaplou možnost background graphics, takže to bylo tím. Teď by tedy mělo být vše v pořádku.

**Comment by nvbach91** [comment]
ok, pekny
