### ISSUE TITLE
podj00-sp1 

### ISSUE THREAD

**Issue by jpodestat** [nvbach91/4IZ268-2020-2021-ZS#109]
https://eso.vse.cz/~podj00/sp1/
https://eso.vse.cz/~podj00/sp1/team/
https://eso.vse.cz/~podj00/sp1/events/
https://eso.vse.cz/~podj00/sp1/playground/
https://eso.vse.cz/~podj00/sp1/contact/
https://eso.vse.cz/~podj00/sp1/assets/css/styles.css

Opraveno:
- misty spatne formatovany kod - zfromátován
- nevhodny font - font změněn na lépe vypadající
- clenove tymu umistete take vedle sebe dokud je misto - dokud je místo, jsou 2 členové vedle sebe (víc mi přišlo nevhodné)
- vsechny obrazky optimalizujte - obrázky jsem zkomprimoval, načítání by již mělo být plynulé 

Vysvětlení:
Logo "Kaufland" slouží jako redirect na stránku sponzora týmu

**Comment by nvbach91** [comment]
A co oprava navigacnich odkazu aby neobsahovaly cast 'index.html' na konci?

**Comment by jpodestat** [comment]
Máte pravdu, už by měla být také opravena.

**Comment by nvbach91** [comment]
nejak vam prestal fungovat favicon

**Comment by jpodestat** [comment]
Kompresor obrázků počítal jen s jpg a favicona byla png, takže se nestáhla vůbec. Už je opraveno.

**Comment by nvbach91** [comment]
- Když se nad tím zamyslíte, asi by bylo vhodné na hlavní stránce přidat nějakou větu, o čem je ten web, důvod, proč by měl uživatel pokračovat ve čtení webu, třeba "jsme banda nadšenců, kteří ..." a přidat nějaký volný rozcestník na další stránky a nespoléhat pouze na navigaci.
- A jinak opravte i ty zdeformované obrázky, např u pana Pavláka
- Stránka Hřiště nemá nadpis?
- Kaufland dejte někam do zápatí a místo toho přidej vlastní logo SWR s tím co vypadá jako ten favicon, nebo to udělejte tak aby bylo jasné, že se jedná o sponzora a ne logo webu
- na stránce Tým se šířkou 1366px vidím pouze 2 sloupce, což je málo, zkuste třeba 3

**Comment by jpodestat** [comment]
1. Doplněn uvítací text s možností redirectu na událost
2. Obrázek jsem ořízl aby odpovídal čtverci
3. Nadpis dopsán
4. Místo neintuitivního kauflandu jsem použil logo týmu - slouží jako redirect na mainpage
5. Při určité šířce jsou viditelné 3 sloupce s členy týmu

**Comment by nvbach91** [comment]
chudák David Pavlák, už tam není, jinak jste ho oříznout nemusel, stačilo ten obrázek zobrazit jako cover výplň kontejneru, jinak asi pěkný
