### ISSUE TITLE
jedv00-sp1

### ISSUE THREAD

**Issue by jedv00** [nvbach91/4IZ268-2020-2021-ZS#110]
oprava:
https://eso.vse.cz/~jedv00/sp1/

https://eso.vse.cz/~jedv00/sp1/epizody/1_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/2_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/3_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/4_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/5_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/6_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/7_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/8_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/9_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/10_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/11_serie.html
https://eso.vse.cz/~jedv00/sp1/epizody/12_serie.html

https://eso.vse.cz/~jedv00/sp1/postavy/lister.html
https://eso.vse.cz/~jedv00/sp1/postavy/kocour.html
https://eso.vse.cz/~jedv00/sp1/postavy/kocanska.html
https://eso.vse.cz/~jedv00/sp1/postavy/kryton.html
https://eso.vse.cz/~jedv00/sp1/postavy/rimmer.html
https://eso.vse.cz/~jedv00/sp1/postavy/holly.html

https://eso.vse.cz/~jedv00/sp1/extra/hlasky.html
https://eso.vse.cz/~jedv00/sp1/extra/zajimavosti.html

https://eso.vse.cz/~jedv00/sp1/sledovani/

https://eso.vse.cz/~jedv00/sp1/css/style.css

- responzivita spociva v nastaveni dynamickych css vlastnosti a hodnot pro width, ne pevnych. viz napr. homepage na 800px sirka okna - **Rozumím, předěláno**
- pouzijte nejaky web font jako Open Sans nebo Roboto z google font - **Přidán web font**
- sjednotte css soubory do jednoho souboru a zvabte se duplicitnich css pravidel - **css sjednoceno a vloženo do složky css**
- css umistete do slozky /css
- obrazky umistete do slozky /img - **všechny obrázky přemístěny do složky img**
- pouzijte techniku slozka/index.html pro hezci odkazy - **udělal jsem tam, kde bylo možné**
- konzistentne pouzijte jeden zpusob pojmenovani css trid, doporucuji zapis s pomlckou - **třídy dosjednoceny**
- obrazky zoptimalizujte - **zoptimalizováno**
- do title bych dal spis naopak `nazev stranky | nazev webu`- **Jo to je pravda, to bude dávat větší smysl - předěláno**

**Comment by nvbach91** [comment]
- responzivita spociva v nastaveni dynamickych css vlastnosti a hodnot pro width, ne pevnych. viz napr. homepage na 800px sirka okna - **Rozumím, předěláno** _porad to neni ono, to telo ma mit nastavene pouze max-width a ne width_
- pouzijte nejaky web font jako Open Sans nebo Roboto z google font - **Přidán web font** - _pouzivejte nejaky google font ktery ma vice styly (tenke, tucne, kurziva) jako open sans nebo roboto, Vas font pro ty textove pasaze zrovna neni moc easy to read na tom cernem pozadi_
- sjednotte css soubory do jednoho souboru a zvabte se duplicitnich css pravidel - **css sjednoceno a vloženo do složky css** - _k_
- css umistete do slozky /css
- obrazky umistete do slozky /img - **všechny obrázky přemístěny do složky img** - _kk_
- pouzijte techniku slozka/index.html pro hezci odkazy - **udělal jsem tam, kde bylo možné** - _to je mozne (a preferovane) vsude_
- konzistentne pouzijte jeden zpusob pojmenovani css trid, doporucuji zapis s pomlckou - **třídy dosjednoceny** _k_
- obrazky zoptimalizujte - **zoptimalizováno** - _k budu verit_
- do title bych dal spis naopak `nazev stranky | nazev webu`- **Jo to je pravda, to bude dávat větší smysl - předěláno** - k

**Comment by jedv00** [comment]
https://eso.vse.cz/~jedv00/sp1/

https://eso.vse.cz/~jedv00/sp1/epizody/1serie/
https://eso.vse.cz/~jedv00/sp1/epizody/2serie/
https://eso.vse.cz/~jedv00/sp1/epizody/3serie/
https://eso.vse.cz/~jedv00/sp1/epizody/4serie/
https://eso.vse.cz/~jedv00/sp1/epizody/5serie/
https://eso.vse.cz/~jedv00/sp1/epizody/6serie/
https://eso.vse.cz/~jedv00/sp1/epizody/7serie/
https://eso.vse.cz/~jedv00/sp1/epizody/8serie/
https://eso.vse.cz/~jedv00/sp1/epizody/9serie/
https://eso.vse.cz/~jedv00/sp1/epizody/10serie/
https://eso.vse.cz/~jedv00/sp1/epizody/10serie/
https://eso.vse.cz/~jedv00/sp1/epizody/11serie/

https://eso.vse.cz/~jedv00/sp1/postavy/lister/
https://eso.vse.cz/~jedv00/sp1/postavy/kocour/
https://eso.vse.cz/~jedv00/sp1/postavy/kocanska/
https://eso.vse.cz/~jedv00/sp1/postavy/kryton/
https://eso.vse.cz/~jedv00/sp1/postavy/rimmer/
https://eso.vse.cz/~jedv00/sp1/postavy/holly/

https://eso.vse.cz/~jedv00/sp1/extra/hlasky/
https://eso.vse.cz/~jedv00/sp1/extra/zajimavosti/

https://eso.vse.cz/~jedv00/sp1/sledovani/

https://eso.vse.cz/~jedv00/sp1/css/style.css

- Responsivita snad už podle představ.
- Font znovu předělán, teď už minimálně mně přijde v pohodě čitelný (je pravda že předchozí nic moc :)). Moc ale nevím, proč nelze používat klasické fonty? Je to kvůli nějaké "funkčnosti" webu, nebo si jen máme vyzkoušet něco dalšího?
- Technika složka/index.html aplikována všude.

**Comment by nvbach91** [comment]
- napr. kdyz chcete aby Vas web vypadal stejne v kazdem zarizeni, jinak jsou i dalsi vyhody web fontu: https://medium.com/hackernoon/web-fonts-when-you-need-them-when-you-dont-a3b4b39fe0ae
- btw zkuste najit nejaky normalni bezpatkovy font na google fonts ktery nezatezuje oci pri cteni a importujte pres `<link>`  v html
- jeste byste mohl opravit verzi pro tisk aby vypadala jako dokument na A4 pak to bude ok, protoze omylem tisknout stranku s cernym pozadim by se nekdo i zabil

![image](https://user-images.githubusercontent.com/20724910/100857101-8cf71180-348c-11eb-81ec-954c2a4761ef.png)

**Comment by jedv00** [comment]
- font použit přes `<link>`
- tisku jsem si nevšiml, již by mělo být v pořádku

**Comment by nvbach91** [comment]
ok pekny ale jeste tu cast 'index.html' musite odstranit z odkazu co jsou v nagivacu..

**Comment by jedv00** [comment]
hotovo

**Comment by nvbach91** [comment]
ok, pekny
