### ISSUE TITLE
pinl01-sp1

### ISSUE THREAD

**Issue by lukyPinky** [nvbach91/4IZ268-2020-2021-ZS#111]
Oprava:
https://eso.vse.cz/~pinl01/sp1/

https://eso.vse.cz/~pinl01/sp1/home/
https://eso.vse.cz/~pinl01/sp1/about/
https://eso.vse.cz/~pinl01/sp1/history/
https://eso.vse.cz/~pinl01/sp1/places/
https://eso.vse.cz/~pinl01/sp1/contact/
https://eso.vse.cz/~pinl01/sp1/contact/results/

https://eso.vse.cz/~pinl01/sp1/assets/styles.css

- uvodni video je prilis male na male obrazovce **-> zvětšeno**
- srovnejte ikony a text v navigaci **-> srovnáno na střed**
- chybi identifikace webu na strankach, treba new york **-> tady si nejsem moc jistý, přidal jsem meta informaci description - New York**
- na verzi pro tisk odstrante veskera ohraniceni **-> odstraněna**
- chybi import tucne verze fontu **-> importováno, tučná slova jdou lépe číst/vidět**
- pridejte nejaky aside sloupec vedle hlavniho obsahu **-> aside sloupec přidán**
- pridejte nejaky text a nejake odkazy na hlavni stranku, aby tam nebylo jen to video - **přidán text, odkaz na knihu a obrázek**
- odstrante 'index.html' z odkazu **-> odstraněno**
- opravte nazev css tridy napr. 'boroughX' aby byl konzistentni s ostatnimi nazvy tridy, doporucuje se zapis s pmlckou -> **opraveno na borough-manhatten, jestli bylo tak myšleno**
- do title dejte take nazev webu, napr 'Zajimava mista | New York City' **-> názvy webu upraveny na doporučený text**

**Comment by nvbach91** [comment]
- uvodni video je prilis male na male obrazovce **-> zvětšeno** _ok_
- srovnejte ikony a text v navigaci **-> srovnáno na střed** _zkuste tam dat display flex a align-items center_
- chybi identifikace webu na strankach, treba new york **-> tady si nejsem moc jistý, přidal jsem meta informaci description - New York** - _tady myslim na vsech strankach by mel byt ten velky text "new york" jako na strance home_
- na verzi pro tisk odstrante veskera ohraniceni **-> odstraněna** - _porad vidim tohle, zkuste doladit ten tisk aby to vypadalo jako dokument pro A4, ta ohraniceni uvidite s zapnutym background graphics v dialogovem okne tisku_
![image](https://user-images.githubusercontent.com/20724910/100812348-18e14d00-343d-11eb-85a6-bf9f501b62e9.png)
- chybi import tucne verze fontu **-> importováno, tučná slova jdou lépe číst/vidět** - _ten wght se da kombinovat do jednoho odkazu kdyz vybirate varianty fontu z google fonts_
- pridejte nejaky aside sloupec vedle hlavniho obsahu **-> aside sloupec přidán** - _na homepage se to zrovna moc nehodi + zkuste mezi ty sloupce pridat nejakou mezeru nebo odstrante to zaobleni rohu, btw opravte to zdeformovani obrazku, ktery je na pozadi stranky_
- pridejte nejaky text a nejake odkazy na hlavni stranku, aby tam nebylo jen to video - **přidán text, odkaz na knihu a obrázek**
- odstrante 'index.html' z odkazu **-> odstraněno** - _ok_
- opravte nazev css tridy napr. 'boroughX' aby byl konzistentni s ostatnimi nazvy tridy, doporucuje se zapis s pmlckou -> **opraveno na borough-manhatten, jestli bylo tak myšleno** - _ok_
- do title dejte take nazev webu, napr 'Zajimava mista | New York City' **-> názvy webu upraveny na doporučený text** - _ok_
