### ISSUE TITLE
tkad06-sp1

### ISSUE THREAD

**Issue by dmitrijt9** [nvbach91/4IZ268-2020-2021-ZS#112]
- [puvodni hodnoceni](https://github.com/nvbach91/4IZ268-2020-2021-ZS/files/5591523/tkad06-assessment.1.txt)

Opraveno:
- pro fonty pouzivejte spis <link> z duvodu konzistence, "vetsi" kompatibility i performance
- chybi prizpusobeni pro tisk - _Pridal jsem media query jen na HP, ostatni stranky mi prisli v poradku pro tisk_
- atribut hid u meta tagu neni validni, vy jste to psal ve Vuejs?
- pridejte vic meta tagu, alespon ty zakladni
- zmensete uvodni obrazek na male obrazovce

https://eso.vse.cz/~tkad06/sp1/
https://eso.vse.cz/~tkad06/sp1/reference/
https://eso.vse.cz/~tkad06/sp1/clanky/
https://eso.vse.cz/~tkad06/sp1/clanky/go-docker-a-gitlab-jednoduche-nastaveni/
https://eso.vse.cz/~tkad06/sp1/clanky/loremipsum/
https://eso.vse.cz/~tkad06/sp1/kontakt/
https://eso.vse.cz/~tkad06/sp1/assets/css/variables.css
https://eso.vse.cz/~tkad06/sp1/assets/css/main.css
https://eso.vse.cz/~tkad06/sp1/assets/css/header.css
https://eso.vse.cz/~tkad06/sp1/assets/css/footer.css
https://eso.vse.cz/~tkad06/sp1/assets/css/reference.css
https://eso.vse.cz/~tkad06/sp1/assets/css/articles.css
https://eso.vse.cz/~tkad06/sp1/assets/css/contact.css

**Comment by nvbach91** [comment]
jeste opravte navigaci tak aby tam vzdy byly vsechny odkazy a ten ktery je aktivni bude zvyrazneny a ne schovany

**Comment by dmitrijt9** [comment]
Nojo, toho jsem si nevsim, to je blby...

Tak uz tam je cela navigace. Diky :)

**Comment by nvbach91** [comment]
ok pekna prace
