### ISSUE TITLE
ulvo00-sp1

### ISSUE THREAD

**Issue by ulvo00** [nvbach91/4IZ268-2020-2021-ZS#113]
Oprava:
https://eso.vse.cz/~ulvo00/sp1/

https://eso.vse.cz/~ulvo00/sp1/tisk/
https://eso.vse.cz/~ulvo00/sp1/design/
https://eso.vse.cz/~ulvo00/sp1/o_nas/
https://eso.vse.cz/~ulvo00/sp1/kontakt/

https://eso.vse.cz/~ulvo00/sp1/css/main.css

- pro nazvy trid pouzijte zapis s pomlckou - **opraveno** 
- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky - **opraveno** 
- soubor main.css dejte do slozky /css - **opraveno**

**Comment by nvbach91** [comment]
Ok, pekny
