### ISSUE TITLE
sikj01-sp01

### ISSUE THREAD

**Issue by sikj01** [nvbach91/4IZ268-2020-2021-ZS#117]
Oprava
https://eso.vse.cz/~sikj01/sp01/homepage
https://eso.vse.cz/~sikj01/sp01/houses
https://eso.vse.cz/~sikj01/sp01/awards
https://eso.vse.cz/~sikj01/sp01/places
https://eso.vse.cz/~sikj01/sp01/seasons
https://eso.vse.cz/~sikj01/sp01/music

https://eso.vse.cz/~sikj01/sp01/css/style.css

- vsechny obrazky optimalizujte - hotovo
- navigaci prestylujte tak aby tam nebylo to podtrzeni a zmena barev navstevovanych odkazu, a take se zbavte tech border-right - hotovo
- chybi import web fontu - přidán
- chybi meta informace - přidány
- pridejte nazev stranky do title - přidán
- chybi prizpusobeni pro tisk - bylo už v původní verzi, mám to tedy chápat jako, že je to provedeno špatně ?
- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky - hotovo
- odstrante 'index.html' z odkazu - odstraňeno
- misty spatne formatovani kodu - mělo by být opraveno
- nevalidni html - validní už je vše, krom <iframe>, to je třeba taky opravit ?

**Comment by nvbach91** [comment]
Na verzi pro tisk vidim tohle:
![image](https://user-images.githubusercontent.com/20724910/100893023-33f2a200-34bb-11eb-957c-f597599a7557.png)
tam je potreba vyladit ten background a ten text, aby vysledek vypadal jako A4 dokument, takze ty odstavce treba zarovnejte doleva atd.

Jinak ten `https://eso.vse.cz/~sikj01/sp01/homepage/` ma byt `https://eso.vse.cz/~sikj01/sp1/`

**Comment by sikj01** [comment]
https://eso.vse.cz/~sikj01/sp1/homepage/
https://eso.vse.cz/~sikj01/sp1/houses/
https://eso.vse.cz/~sikj01/sp1/awards/
https://eso.vse.cz/~sikj01/sp1/places/
https://eso.vse.cz/~sikj01/sp1/seasons/
https://eso.vse.cz/~sikj01/sp1/music/

https://eso.vse.cz/~sikj01/sp1/css/style.css

Nedošlo mi, že si musím zakliknout "background", teď už by měl být tisk v pořádku.
Odkazy taky opraveny.

**Comment by nvbach91** [comment]
- zkontrolujte navigacni odkazy, nekde prestaly fungovat
- opet homepage ma byt dostupny pod odkaz `https://eso.vse.cz/~sikj01/sp1/`

**Comment by sikj01** [comment]
https://eso.vse.cz/~sikj01/sp1/
https://eso.vse.cz/~sikj01/sp1/houses/
https://eso.vse.cz/~sikj01/sp1/awards/
https://eso.vse.cz/~sikj01/sp1/places/
https://eso.vse.cz/~sikj01/sp1/seasons/
https://eso.vse.cz/~sikj01/sp1/music/

https://eso.vse.cz/~sikj01/sp1/css/style.css

už by mělo fungovat vše

**Comment by nvbach91** [comment]
ok dobry
