### ISSUE TITLE
potp04 - sp1

### ISSUE THREAD

**Issue by petrpotmesil** [nvbach91/4IZ268-2020-2021-ZS#120]
Opraveno
https://eso.vse.cz/~potp04/sp1/
https://eso.vse.cz/~potp04/sp1/o-mne/
https://eso.vse.cz/~potp04/sp1/ja-a-youtube/
https://eso.vse.cz/~potp04/sp1/zkusenosti/
https://eso.vse.cz/~potp04/sp1/projekty/
https://eso.vse.cz/~potp04/sp1/kontakt/

https://eso.vse.cz/~potp04/sp1/css/stylizace.css

**Comment by nvbach91** [comment]
oprava toho pretekani nespociva v tom ze tam date overflow: auto :) ted je tam skoro všude scrollbar když na to najedu myškou

**Comment by petrpotmesil** [comment]
Rozumím. Přišlo mi to jako nejpraktičtější řešení, protože chci zachovat konstantní výšku všech elementů. Jakmile bych nechal výšku přizpůsobit se speciálně každému textu či obrázku, nepůsobilo by to esteticky. 

Mohl bych se zeptat, jestli byste mi doporučil jiné řešení, které je podle vás optimální? Mě samotnému totiž nejvíc sedlo toto. 

Ostatní opravy jsou v pořádku? 

Předem děkuji za odpověď.

**Comment by nvbach91** [comment]
- Vsak staci nechat u kontejneru obrazku overflow: hidden a u textu asi muzete nechat auto
- jinak je tady dalsi chyba pretekani obsahu z sirku okna
![image](https://user-images.githubusercontent.com/20724910/101280800-6d812100-37cb-11eb-9584-fd639d663713.png)

**Comment by petrpotmesil** [comment]
Oba problémy opraveny.

**Comment by nvbach91** [comment]
stejnym zpusobem jeste opravte ty videa

**Comment by petrpotmesil** [comment]
Videa taktéž opravena.

**Comment by nvbach91** [comment]
ok
