### ISSUE TITLE
udoy00-sp1

### ISSUE THREAD

**Issue by evgeniyMtl** [nvbach91/4IZ268-2020-2021-ZS#121]

**Comment by evgeniyMtl** [comment]
https://eso.vse.cz/~udoy00/sp1/index.html
https://eso.vse.cz/~udoy00/sp1/html/education.html
https://eso.vse.cz/~udoy00/sp1/html/skills.html
https://eso.vse.cz/~udoy00/sp1/html/experience.html
https://eso.vse.cz/~udoy00/sp1/html/languages.html

https://eso.vse.cz/~udoy00/sp1/css/styles.css
https://eso.vse.cz/~udoy00/sp1/js/main.js

[komentare.docx](https://github.com/nvbach91/4IZ268-2020-2021-ZS/files/5632553/komentare.docx)
- odkazy na externi web by se mely otevrit v nove zalozce - opraveno
- pouzivejte telefonni a emailove odkazy - opraveno
- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky odstrante 'index.html' z odkazu - opraveno
- odstrante cast 'index.html' z odkazu - opraveno
- obrazek nechte zoptimalizovat - opraveno
- pouzivejte nejake ikony u polozek v navigaci - podle me je to zbytecne, jednoduche ozneceni ctvreckama je vice esteticke pro zivotopis a u odkazu na socialni site - opraveno
- odstrante javascript - je tam pro mobilni verzi webu, zkuste to z mobilu. Nebylo uvedeno v podminkach zakaz pouziti JS, 
- chybi meta informace - opraveno
- u neparovych tagu nepouzivejte zakonceni /> - opraveno
- pouzivejte semanticke tagy - opraveno
- chybi zvyrazneni aktivni polozky navigace - opraveno
- chybi prizpusobeni pro tisk - verze pro tisk vypada presne tak, jak jsem to chtel, je tam zachovana vetsina stylovani a vypada to prehledne a nevidim duvod delat to jinak

- pridejte footer – je k nicemu v ramci formatu webu a kdyby byl tak narusuje puvodne mysleny design

**Comment by nvbach91** [comment]
no dobře jak chcete
- vím co Váš skript dělá, ale javascript není povolený v SP1, a tu Vaše "funkcionalitu" by se dalo udělat pomocí kombinace HTML a CSS (např. checkboxu a pseudo selektoru)
- nerozumím tomu proč máte složku stránky education, skills, ... ve slozce html
- footer, např. v podobě pruhu s copyrightem, může být i v životopisu, a kdybyste ho nechtěl tisknout, stačí ho schovat
- na verzi pro tisk schovejte tu barvu pozadí, jinak mi po jendom tisku dojde inkoust, a také zkuste změnit barvu písma aby to bylo čitelnější na bílém pozadí
- a Váš způsob používání sémantických tagů neodpovídá tomu co jsem já učil na hodinách

**Comment by evgeniyMtl** [comment]
https://eso.vse.cz/~udoy00/sp1/index.html
https://eso.vse.cz/~udoy00/sp1/education/index.html
https://eso.vse.cz/~udoy00/sp1/skills/index.html
https://eso.vse.cz/~udoy00/sp1/experience/index.html
https://eso.vse.cz/~udoy00/sp1/languages/index.html

https://eso.vse.cz/~udoy00/sp1/css/styles.css
https://eso.vse.cz/~udoy00/sp1/js/main.js

- vím co Váš skript dělá, ale javascript není povolený v SP1, a tu Vaše "funkcionalitu" by se dalo udělat pomocí kombinace HTML a CSS (např. checkboxu a pseudo selektoru) - opravdu predtim nez jsem si dovolil pouzit JS prosel jsem stranky:
https://github.com/nvbach91/4IZ268-2020-2021-ZS/wiki/Pokyny-SP1
https://4iz268.github.io/zakonceni/stranky/
a nenasel jsem nic o tom, ze JS neni povolen, navic veta "CSS a případný JavaScript jsou odděleny od obsahu stránek" me ujistila v moznosti ho pouziti
- nerozumím tomu proč máte složku stránky education, skills, ... ve slozce html - opraveno
- footer, např. v podobě pruhu s copyrightem, může být i v životopisu, a kdybyste ho nechtěl tisknout, stačí ho schovat - pridano
- na verzi pro tisk schovejte tu barvu pozadí, jinak mi po jendom tisku dojde inkoust, a také zkuste změnit barvu písma aby to bylo čitelnější na bílém pozadí - opraveno
- a Váš způsob používání sémantických tagů neodpovídá tomu co jsem já učil na hodinách - ano, protoze jsem je pridaval uz v ramci opravy a snazil jsem je dat tam, kde to odpovida v podstate te semantice, pokud bych cely layout navrhoval ze zacatku bylo by to jinak.

**Comment by nvbach91** [comment]
ok
