### ISSUE TITLE
toho00-sp1

### ISSUE THREAD

**Issue by toho00** [nvbach91/4IZ268-2020-2021-ZS#122]
oprava:
https://eso.vse.cz/~toho00/sp1/
https://eso.vse.cz/~toho00/sp1/bio/
https://eso.vse.cz/~toho00/sp1/wedding/
https://eso.vse.cz/~toho00/sp1/cover/
https://eso.vse.cz/~toho00/sp1/gear/
https://eso.vse.cz/~toho00/sp1/contact/

https://eso.vse.cz/~toho00/sp1/css/styles.css

- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky odstrante 'index.html' z odkazu
- krome souboru homepage.html, ten by mel byt index.html v korene webu
- odstrante cast 'index.html' z odkazu
- pouzivejte html entity
- odstranil bych pozadi tech neaktivnich polozek v navigaci
- pouzivejte relativni odkazy na stranky a zdroje
- target="_self" se psat nemusi
- do title pridejte i nazev webu, (nazev stranky | nazev webu)
- opravte efekt pri hoveru na obrazek/video na strance svatby a covery
- do nazvu webu pridejte asi tu profesi (photography nebo video guru...)

snad jsem nic nepřehlédnul a opravil jsem vše.

**Comment by nvbach91** [comment]
ok pekny
