### ISSUE TITLE
sinj04-sp1

### ISSUE THREAD

**Issue by BlazeCZ** [nvbach91/4IZ268-2020-2021-ZS#125]
https://eso.vse.cz/~sinj04/sp1/
https://eso.vse.cz/~sinj04/sp1/datadisky/
https://eso.vse.cz/~sinj04/sp1/svet/
https://eso.vse.cz/~sinj04/sp1/svet/frakce/
https://eso.vse.cz/~sinj04/sp1/platba/

https://eso.vse.cz/~sinj04/sp1/styles/index.css

- vize omezte sirku radku textu, jedna se to typografickou chybu kdyz je tak dlouhy text na sirku - spatne se cte - **zmenšena šířka odstavců**
- opravte zdeformovane obrazky - **upravena velikost**
- font-family se dava spise do body - **opraveno**
- normalni font-weight pro cteni je 400, vy mate importovanou pouze verzi 100 - **změněno**
- velikost pisma pro cteni je prilis velke, byva to max 14px - **změněno** 
- sjednotte css soubory do jednoho souboru a zbavte se duplicitnich css pravidel - **sjednoceno**
- kdyz dam tisk tak vidim cernou stranku papiru - odstrante cerne pozadi - **pozadí odstraněno**

**Comment by nvbach91** [comment]
- chybi import font-weight 700 pro bold font, zaklikavaji se vetsinou 400 a 700
- asi byste mohl odstranit ty horizontalni cary na verzi pro tisk

**Comment by BlazeCZ** [comment]
chybi import font-weight 700 pro bold font, zaklikavaji se vetsinou 400 a 700 - **doplněno**
asi byste mohl odstranit ty horizontalni cary na verzi pro tisk - **odstraněny**

**Comment by BlazeCZ** [comment]
up

**Comment by nvbach91** [comment]
ok staci
