### ISSUE TITLE
Dotaz SP1

### ISSUE THREAD

**Issue by apatenko369** [nvbach91/4IZ268-2020-2021-ZS#13]
Dobrý den,
chtěl bych se zeptat co přesně tímto myslíte?
![image](https://user-images.githubusercontent.com/72221824/98035615-162d1100-1e19-11eb-82eb-fa21f09b44cd.png)

A dále zda toto mám opravit a poslat vám to ke kontrole?

Děkuji. Ivan Apatenko

**Comment by nvbach91** [comment]
Vaše html soubory by měly být pojmenovány jako index.html a budete je dávat do složek které pojmenujete podle toho jak se stránka jmenuje.

Viz: https://github.com/nvbach91/4IZ268-2020-2021-ZS/wiki/LAB03 u struktury webu

Opravený návrh pošlete znova přes formulář.
