### ISSUE TITLE
apai00 - SP1

### ISSUE THREAD

**Issue by apatenko369** [nvbach91/4IZ268-2020-2021-ZS#133]
https://eso.vse.cz/~apai00/sp1/index.html
https://eso.vse.cz/~apai00/sp1/product/index.html
https://eso.vse.cz/~apai00/sp1/sponsor/index.html
https://eso.vse.cz/~apai00/sp1/contact/index.html
https://eso.vse.cz/~apai00/sp1/author/index.html

https://eso.vse.cz/~apai00/sp1/attachment/css/styles.css

**Comment by nvbach91** [comment]
piste sem co vsechno jste opravoval

- stale mate 'index.html' v odkazech
- prepiste `<table>` na `<div>`
- k cemu je ten font dancing script?
- zmente barvu pisma na bilou u aktivnich polozek navigace
- opravte back to top odkaz aby pouzival id a ne cely url

**Comment by apatenko369** [comment]
Dobrý den,
stale mate 'index.html' v odkazech - OPRAVENO
prepiste `<table>` na `<div>` - OPRAVENO
k cemu je ten font dancing script? - ODSTRANĚNO
zmente barvu pisma na bilou u aktivnich polozek navigace - OPRAVENO
opravte back to top odkaz aby pouzival id a ne cely url  - OPRAVENO

https://eso.vse.cz/~apai00/sp1/index.html
https://eso.vse.cz/~apai00/sp1/product/index.html
https://eso.vse.cz/~apai00/sp1/sponsor/index.html
https://eso.vse.cz/~apai00/sp1/contact/index.html
https://eso.vse.cz/~apai00/sp1/author/index.html

https://eso.vse.cz/~apai00/sp1/attachment/css/styles.css
