### ISSUE TITLE
doss02 - sp1

### ISSUE THREAD

**Issue by SDostalkova** [nvbach91/4IZ268-2020-2021-ZS#134]
https://eso.vse.cz/~doss02/sp1/
https://eso.vse.cz/~doss02/sp1/about/
https://eso.vse.cz/~doss02/sp1/wanthelp/
https://eso.vse.cz/~doss02/sp1/needhelp/
https://eso.vse.cz/~doss02/sp1/events/
https://eso.vse.cz/~doss02/sp1/articles/
https://eso.vse.cz/~doss02/sp1/contacts/

https://eso.vse.cz/~doss02/sp1/assets/css/main.css

- z odkazu odstrante cast 'index.html' **- opraveno**
- opravte navigaci tak, aby pri najeti mysi zustaly polozky na svych mistech **- opraveno**
- v aktivni polozce navigace nechte text misto obrazku na pozadi **- opraveno**
- zmente hodnotu atributu lang **- opraveno**
- pouzijte vhodnejsi font, napr open sans nebo roboto **- opraveno**
- pouzivejte take telefonni odkaz **- opraveno**
- bloky textu na hlavni strance zarovnejte doleva a na kazdem radku nechte max. 3 sloupce **- opraveno**
- text-align center se nehodi takto vsude - chápu, tady se více hodí zarovnání doleva
- do title piste nazev stranky a nazev webu **- opraveno**
- sjednotte css soubory do jednoho souboru a zbavte se duplicitnich css pravidel **- opraveno**
- opravte verzi pro tisk stranky o nas, chci pomoci, potrebuji pomoc, akce, clanky (mensi pismo, zarovnani textu, apod) **- opraveno**
- doplnte meta informace **- opraveno**

**Comment by nvbach91** [comment]
- velikost fontu u pasazi textu prilis velka, dejte tam 14
- a stranka na 800x600 neni v poradku (pretekani obsahu stranky z sirky okna)
- width 31% neni spravne reseni, ma to byt calc(100% / 3) a misto marginu padding

**Comment by SDostalkova** [comment]
- velikost fontu změněna
- stranka 800x600 vyřešena
- width - opraveno

**Comment by nvbach91** [comment]
pěkné, a pěknější by bylo kdybyste omezila šířku textu aby na každém řádku bylo max cca 50 znaků
tady je něco k přečtení https://medium.com/@v.khlopotova/the-main-rules-of-typography-ce53d297f7dd
