### ISSUE TITLE
ivaa07-SP1

### ISSUE THREAD

**Issue by ivajlovska** [nvbach91/4IZ268-2020-2021-ZS#135]

**Comment by ivajlovska** [comment]
https://eso.vse.cz/~ivaa07/sp1/index.html
https://eso.vse.cz/~ivaa07/sp1/energydiet.html
https://eso.vse.cz/~ivaa07/sp1/skinmain.html
https://eso.vse.cz/~ivaa07/sp1/skinbody.html
https://eso.vse.cz/~ivaa07/sp1/skincare.html
https://eso.vse.cz/~ivaa07/sp1/makeup.html
https://eso.vse.cz/~ivaa07/sp1/home.html
https://eso.vse.cz/~ivaa07/sp1/vitamin.html
https://eso.vse.cz/~ivaa07/sp1/parfume.html
https://eso.vse.cz/~ivaa07/sp1/contacts.html
https://eso.vse.cz/~ivaa07/sp1/css/index-style.css
https://eso.vse.cz/~ivaa07/sp1/css/shopskinstyle.css
https://eso.vse.cz/~ivaa07/sp1/css/skinstyle.css


Dobrý den, opravila jsem aktivní linky, meta, verze pro tisk apod.

**Comment by nvbach91** [comment]
piste sem prosim seznam chyb a co preste jste opravovala / neopravovala a proc. dekuji

**Comment by ivajlovska** [comment]
Dobrý den, 

1. chybi zvyrazneni aktivnich polozek v navigaci - hotovo
1. nemichejte odkazy na sekce v strance s odkazy na jine stranky - hotovo
1. html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky - nevím proč je to nutné, chci to mít tak jak je
1. sjednotte css soubory do jednoho souboru a odstrante duplicitni css pravidla - udělala jsem tak jako je jednodušší pro mě, chci je mít v různých souborech pro různé účely. 
1. odstrante ten efekt navigace - hotovo
1. obrazky optimalizujte - doplněno width
1. chybi favicon - hotovo
1. produkty zobrazujte nekolik vedle sebe a zajistete aby bylo dost mista pro ne - libí se mi tak jak je
1. pouzijte emailovy odkaz - hotovo
1. zmensete leve menu - pro mě má optimální velikost 
1. chybi prizpusobeni pro tisk - hotovo
1. veskery kod css i html naformatujte - tomu nerozumím 
1. proc obcas vidim tabulator a obcas mezery u indentace kodu? - pouzijte pouze jeden z nich - to nevím, použivala jsem jiný redaktor, ted k němu již nemám přistup - vypršela doba zdarma, v VSC i když smažu řádek  a pak dám Tab tak zase mi ukazuje tečky jestli chápu správně ten problém. 
1. chybi meta informace - doplněno 
1. chybi import pouziteho web fontu - mám link na font
1. na male obrazovce vidim pouze menu... - to jsem se snažila opravit 
1. slozku SP1 prejmenujte na sp1 - hotovo

**Comment by nvbach91** [comment]
1 - polozkam v navigaci tedy pridejte padding doleva a doprava, obsah tagu h1 nemuze byt pokazde "menu"
3 - tohle je problematika tykajici se "clean url", jinak duvody pro Vas: srozumitelnost pro cloveka, pouzitelnost, pristupnost, seo, search engine ranking, apod., pokud jste chodila na prednasky a delala se mnou ta cviceni tak urcite vite o cem je rec
4 - pokud chcete mit vice css souboru tak nesmite v nich opakovat stejna pravidla a musite mit na to jasny system prepouzivani tech pravidel, napr jeden soubor pro spolecne styly na vsech strankach, a kazda stranka ma navic rozsirujici css pravidla, mimochodem je mnohdy lepsi mit vsechna pravidla v jednom souboru a rozdelit ho na sekce vyhrazene pro urcite stranky a tim padem nebudete mit problem s opakovanim stejnych css pravidel
6 - tim "optimalizujte" myslim to co jsme rikali na [3. cv. ](https://github.com/nvbach91/4IZ268-2020-2021-ZS/wiki/LAB03)
7 - do title dejte nazev stranky a nazev webu, napr "Uvod | NL Store", "Zdrava strava | NL Store"
8 - to je skoda kdyz je nechate v tom stavu, a navic tohle je urcite spatne 
![image](https://user-images.githubusercontent.com/20724910/101285580-45eb8200-37e6-11eb-8cb2-41f758b6b486.png)
10 - rikate optimalni ale zbytecne to zabira misto na strance
![image](https://user-images.githubusercontent.com/20724910/101285856-daa2af80-37e7-11eb-994e-8569103b7427.png)
11 - na verzi pro tisk zruste tmave pozadi a preusporadejte tu prvni stranu aby se netisklo tolik zbytecneho obsahu
12 - pokud jste chodila na cviceni, urcite vite ze kod musi byt zformatovan (indentace, syntaxe, ...) pomoci nejakeho formatovace, aby se dalo kod lepe cist, ve VS Code to je Alt+Shift+F
13 - to formatovani kodu za Vas ten problem vyresi, kazdopadne neni dobre michat mezery a tabulatory pro indentaci kodu
15 - zkuste mi napsat ktere vsechny fonty pouzivate v ramci sveho webu, dejte take pozor na jake varianty dotycneho fontu pouzivate a zkontrolujte import
16 - na male obrazovce zmensete logo, preusporadejte navigaci prvky, aby se jich veslo co nejvice na jendom radku, pripadne 2 radky, zmensete / schovejte uvodni obrazek na kazde strance, ... proc - viz obrazek
![image](https://user-images.githubusercontent.com/20724910/101285486-aded9880-37e5-11eb-922a-309907db62f2.png)

**Comment by ivajlovska** [comment]
1 - co bych měla napsat kromě menu prosím?
4 - používám je pravě s různým obsahem, možna musím tam jen vynechat to body, jinak každá má svoje
8 - mám to u sebe pěkně safari a chrome
<img width="989" alt="image" src="https://user-images.githubusercontent.com/72252735/101340125-9e229280-387f-11eb-9147-3d4c94ef643c.png">
15 - font-family: 'Open Sans', Helvetica, Arial, sans-serif;

**Comment by nvbach91** [comment]
1 - h1 by melo slouzit jako znacka pro nazev stranky
15 - myslim ze jsem tam videl i Roboto

**Comment by ivajlovska** [comment]
Dobrý den,

opravila jsem web podle posledních poznámek
