### ISSUE TITLE
novd35-sp1

### ISSUE THREAD

**Issue by dnovosad1** [nvbach91/4IZ268-2020-2021-ZS#136]
Oprava
https://eso.vse.cz/~novd35/sp1
https://eso.vse.cz/~novd35/sp1/css/main.css
https://eso.vse.cz/~novd35/sp1/css/reset.css
https://eso.vse.cz/~novd35/sp1/css/print.css

1. Css soubory do složky css
2. Odstraněno tlačítko zjistěte víc(chtěl jsem mít  původně v horní sekci nějaké CTA, ale nakonec se mi to tam zdálo navíc)
3. Přidán offset pro linky v navigaci
4. Pridano textarea do formu
5. Změna input type ve formu
6. Přidán tel. odkaz
7. Pridana verze pro tisk
8. Odkazy na externi web by se mely otevrit v nove zalozce( tady nevím co myslíte? Linky tam mam jen na sociální sítě a ty se otevírají v nové záložce)

**Comment by nvbach91** [comment]
8 - co ten odkaz `href="www.https://www.webchimp.com"`?
7 - na te verzi pro tisk byste mohl preusporadat informace tak aby to vypadalo jako dokument A4 ve wordu a tak aby na sebe navazovaly pres ty stranky bez preruseni, ty stiny se tam take nedavaji a nechte tam nazev webu
3 - ten druhy odkaz `jak to funguje` ma skocit spis na ten nadpis h2

![image](https://user-images.githubusercontent.com/20724910/101281266-5f80cf80-37ce-11eb-951f-eacafa95200a.png)
