### ISSUE TITLE
vetj00-sp1

### ISSUE THREAD

**Issue by vetrovskyj** [nvbach91/4IZ268-2020-2021-ZS#137]
**Oprava**

https://eso.vse.cz/~vetj00/SP1/home/index.html
https://eso.vse.cz/~vetj00/SP1/info/index.html
https://eso.vse.cz/~vetj00/SP1/cenik/index.html
https://eso.vse.cz/~vetj00/SP1/vyprodej/index.html
https://eso.vse.cz/~vetj00/SP1/kontakt/index.html

https://eso.vse.cz/~vetj00/SP1/assets/css/style.css

- hlavni sloupec na strance o nas bych udelal jeste uzsi, aby nebyl text tak dlouhy do sirky stranky **- opraveno**
- pouzivejte emailovy a telefonni odkaz **- opraveno**
- misto te staticke mapy pridejte iframe na google maps se znackou v dane adrese **- opraveno**
- font-family se dava spise do body a ne do * **- opraveno**
- na verzi pro tisk jsou obrazky prilis velke, take odstrante obrazek na pozadi **- opraveno**
- vyraznejsim zpusobem zvyraznete aktivni polozku navigace **- opraveno**
- presunul bych stranky info, cenik, vyprodej a kontakt na uroven hlavni stranky **- opraveno**

**Comment by nvbach91** [comment]
- odkazy by mely byt nejaky zpusobem odliseny od zbytku textu (viz email, telefon na strance kontakt)
- optimaluzujte obrazky, nestaci pouze komprese, vidim tam obrazky s 4mega
- stranka home ma byt dostupny pod odkaz `https://eso.vse.cz/~vetj00/SP1/`

**Comment by vetrovskyj** [comment]
https://eso.vse.cz/~vetj00/SP1/

https://eso.vse.cz/~vetj00/SP1/index.html
https://eso.vse.cz/~vetj00/SP1/info/index.html
https://eso.vse.cz/~vetj00/SP1/cenik/index.html
https://eso.vse.cz/~vetj00/SP1/vyprodej/index.html
https://eso.vse.cz/~vetj00/SP1/kontakt/index.html

https://eso.vse.cz/~vetj00/SP1/assets/css/style.css

- odkazy by mely byt nejaky zpusobem odliseny od zbytku textu (viz email, telefon na strance kontakt) - **opraveno**
- optimaluzujte obrazky, nestaci pouze komprese, vidim tam obrazky s 4mega - **opraveno**, nevětší obrázek má nyní 219 kB
- stranka home ma byt dostupny pod odkaz https://eso.vse.cz/~vetj00/SP1/ - **opraveno**, ale moc nerozumím, jak jste tedy myslel: "presunul bych stranky info, cenik, vyprodej a kontakt na uroven hlavni stranky"

**Comment by nvbach91** [comment]
no takhle jsem to myslel, tohle melo byt domluveny uz v navhru...
jinak co se vam libi vic, vlevo nebo vpravo?
![image](https://user-images.githubusercontent.com/20724910/101504176-33eb1a00-3973-11eb-9aab-e0abc21e584c.png)

**Comment by vetrovskyj** [comment]
Úrovňově to takto v podstatě bylo v návrhu i v první odevzdané verzi, jen se stránky nacházely ještě o jednu složku hlouběji, proto jsem tu první opravu asi špatně pochopil.
Hezčí je nejspíš doopravdy Váš návrh vpravo. Zarovnání do bloku bylo při zmenšené velikosti webu zbytečné.
