### ISSUE TITLE
seip00-sp1

### ISSUE THREAD

**Issue by voiran** [nvbach91/4IZ268-2020-2021-ZS#138]
Oprava SP1

https://eso.vse.cz/~seip00/sp1/index.html
https://eso.vse.cz/~seip00/sp1/pc/index.html
https://eso.vse.cz/~seip00/sp1/ntb/index.html
https://eso.vse.cz/~seip00/sp1/monitor/index.html
https://eso.vse.cz/~seip00/sp1/klavesnice/index.html
https://eso.vse.cz/~seip00/sp1/mys/index.html

https://eso.vse.cz/~seip00/sp1/css/styles.css

Přejmenování a rozdělení HTML souborů
Upraveny rozměry stránky a verze pro tisk
Border u navigačních prvků odebrán
Dolpněny meta informace
HTML entity - alespoň nějaké jsem tam dal
Přidán odkaz na hl. stránku do loga
Přidání/úprava responzibility
Title stránek upraven
H1 doplněn na každou stránku
Seskupení všech CSS souborů do jednoho a promazání zbytečných/duplicitních pravidel

**Comment by nvbach91** [comment]
- opravte pretekani obsahu stranky mimo okna
![image](https://user-images.githubusercontent.com/20724910/101281626-585ac100-37d0-11eb-912b-8d0d78ce5346.png)
- opravte zobrazovani loga (zachovat jeho puvodni rozmer vzdycky) a na male obrazovce a ho zmensete
- zmente typ kurzoru na tlacitkach u produktu
- responzibilita vs responzivita...

**Comment by voiran** [comment]
Přetékání odstraněno
Logo má statickou velikost
Kurzor se na tlačítkách mění
a pardon za RESPONZIVITU, ve čtyři ráno jsem se prostě upsal

Odkazy jsou stejné
