### ISSUE TITLE
gerv03- sp1

### ISSUE THREAD

**Issue by Pulman3** [nvbach91/4IZ268-2020-2021-ZS#139]
Oprava sp1

- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky --> opraveno.
- chybi import tucne verze fontu --> opraveno.
- znak copyright, ne zavinac --> opraveno.
- typograficka chyba - dlouhy text na sirku stranky, zkuste zmensit sirku stranky na max cca 1280px a vycentrovat --> opraveno
- u img tagu odstrante atribut height nebo tam dejte hodnotu ktera odpovida rozmeru obrazku --> opraveno.

Nerozumím však, proč se mi po nahrání na eso server nezobrazuje css a obrázky. Po spuštění na live serveru ve visual studio code všechno funguje, jak má.  Předtím jsem tento problém s eso serverem vyřešil tak, že jsem místo /css/index.css napsal css/index.css. Tentokrát to však nefunguje.

https://eso.vse.cz/~gerv03/sp1-oprava/úvod

https://eso.vse.cz/~gerv03/sp1-oprava/úvod/index.html
https://eso.vse.cz/~gerv03/sp1-oprava/novinky_a_události/index.html
https://eso.vse.cz/~gerv03/sp1-oprava/klasické_otužování/index.html
https://eso.vse.cz/~gerv03/sp1-oprava/wim_hofova_metoda/index.html
https://eso.vse.cz/~gerv03/sp1-oprava/jak_začít/index.html
https://eso.vse.cz/~gerv03/sp1-oprava/zdravotní_benefity_KO/index.html
https://eso.vse.cz/~gerv03/sp1-oprava/zdravotní_benefity_WHM/index.html

https://eso.vse.cz/~gerv03/sp1/css/index.css
https://eso.vse.cz/~gerv03/sp1/css/news.css
https://eso.vse.cz/~gerv03/sp1/css/otuzovani.css
https://eso.vse.cz/~gerv03/sp1/css/otuzovani-benefity.css
https://eso.vse.cz/~gerv03/sp1/css/print.css
https://eso.vse.cz/~gerv03/sp1/css/tutorial.css
https://eso.vse.cz/~gerv03/sp1/css/wimhof.css
https://eso.vse.cz/~gerv03/sp1/css/wimhof-benefity.css

**Comment by nvbach91** [comment]
1. součástí url nemá být znaky s diakritikou - přejmenujte
1. domovská stránka/úvod má být pod odkazem 'https://eso.vse.cz/~gerv03/sp1/' - to je jediná výjimka, tj bez slozky
1. místo podtržítek v názvech těch složek dejte pomlčky
1. z odkazu v navigaci odstrante cast 'index.html'
1. duvod proc vam to nefunguje: vy pouzivate absolutni odkazy a vychazite z korene webu (zacinate znakem `/` v odkaze na ty soubory), pouzivejte relativni odkazy (bez `/` na zacatku) a bude vam to fungovat
1. opravenou verzi sp1 nahrajte do sp1 a ne sp1-oprava

**Comment by Pulman3** [comment]
součástí url nemá být znaky s diakritikou - přejmenujte  --> opraveno.
domovská stránka/úvod má být pod odkazem 'https://eso.vse.cz/~gerv03/sp1/' - to je jediná výjimka, tj bez slozky --> opraveno
místo podtržítek v názvech těch složek dejte pomlčky --> opraveno
z odkazu v navigaci odstrante cast 'index.html' --> opraveno
opravenou verzi sp1 nahrajte do sp1 a ne sp1-oprava --> opraveno

duvod proc vam to nefunguje: vy pouzivate absolutni odkazy a vychazite z korene webu (zacinate znakem / v odkaze na ty soubory), pouzivejte relativni odkazy (bez / na zacatku) a bude vam to fungovat. 
-->
Všude jsem to opravil na relativní odkazy (bez / na začátku) a stále to nefunguje. + na homepage se nezobrazuje opravený max-width a vycentrování. Nerozumím tomu, na live serveru mi to fungovalo.

https://eso.vse.cz/~gerv03/sp1

https://eso.vse.cz/~gerv03/sp1/novinky-a-udalosti
https://eso.vse.cz/~gerv03/sp1/klasicke-otuzovani
https://eso.vse.cz/~gerv03/sp1/wim-hofova-metoda
https://eso.vse.cz/~gerv03/sp1/jak-zacit
https://eso.vse.cz/~gerv03/sp1/zdravotni-benefity-KO
https://eso.vse.cz/~gerv03/sp1/zdravotni-benefity-WHM

https://eso.vse.cz/~gerv03/sp1/css/index.css
https://eso.vse.cz/~gerv03/sp1/css/news.css
https://eso.vse.cz/~gerv03/sp1/css/otuzovani.css
https://eso.vse.cz/~gerv03/sp1/css/otuzovani-benefity.css
https://eso.vse.cz/~gerv03/sp1/css/print.css
https://eso.vse.cz/~gerv03/sp1/css/tutorial.css
https://eso.vse.cz/~gerv03/sp1/css/wimhof.css
https://eso.vse.cz/~gerv03/sp1/css/wimhof-benefity.css

**Comment by nvbach91** [comment]
musite chapat ze relativni odkaz znamena relativni k aktualnimu mistu kde se nachazite, napr. na strance `jak-zacit` mate odkaz na css soubor v podobe `css/turorial.css`, to znamena `najdi mi soubor tutorial.css ktery se nachazi ve slozce css, ktera se nachazi ve slozce, ve ktere zrovna jsem`, bohuzel ale zrovna v aktualnim adresari nemate zadnou slozku ktera by se jmenovala `css`. ta se nachazi v adresari o uroven vys... doporucuji se podivat na 3. cviceni  https://github.com/nvbach91/4IZ268-2020-2021-ZS/wiki/LAB03

**Comment by Pulman3** [comment]
Odkazy opraveny. 
https://eso.vse.cz/~gerv03/sp1

https://eso.vse.cz/~gerv03/sp1/novinky-a-udalosti
https://eso.vse.cz/~gerv03/sp1/klasicke-otuzovani
https://eso.vse.cz/~gerv03/sp1/wim-hofova-metoda
https://eso.vse.cz/~gerv03/sp1/jak-zacit
https://eso.vse.cz/~gerv03/sp1/zdravotni-benefity-KO
https://eso.vse.cz/~gerv03/sp1/zdravotni-benefity-WHM

https://eso.vse.cz/~gerv03/sp1/css/index.css
https://eso.vse.cz/~gerv03/sp1/css/news.css
https://eso.vse.cz/~gerv03/sp1/css/otuzovani.css
https://eso.vse.cz/~gerv03/sp1/css/otuzovani-benefity.css
https://eso.vse.cz/~gerv03/sp1/css/print.css
https://eso.vse.cz/~gerv03/sp1/css/tutorial.css
https://eso.vse.cz/~gerv03/sp1/css/wimhof.css
https://eso.vse.cz/~gerv03/sp1/css/wimhof-benefity.css

**Comment by nvbach91** [comment]
velmi pekne
