### ISSUE TITLE
SP2 návrh - otázka

### ISSUE THREAD

**Issue by jedv00** [nvbach91/4IZ268-2020-2021-ZS#140]
Dobrý večer,

vytvořil jsem překrásný Wireframe pomocí Balsamiq Wireframes. Bohužel ale do google formuláře nemohu vložit pdf nebo jakýkoli jiný formát, který mi to umožní vyexportovat. 

Mohu tam ale vložit každý Wireframe zvlášť jako obrázek, nebude to už ale prolinkované atd, jen x obrázků. 

Je to takto v pohodě, nebo mám návrh předělat či poslat jiným způsobem? 

Díky moc :).

**Comment by nvbach91** [comment]
Ano, bohatě stačí screenshot, nejlépe jen jeden (příp. složený z více obrázků)
