### ISSUE TITLE
novb12-sp1

### ISSUE THREAD

**Issue by bnaru** [nvbach91/4IZ268-2020-2021-ZS#141]
https://eso.vse.cz/~novb12/sp1/
https://eso.vse.cz/~novb12/sp1/historie/
https://eso.vse.cz/~novb12/sp1/kontakty/
https://eso.vse.cz/~novb12/sp1/zavody/
https://eso.vse.cz/~novb12/sp1/obleceni/
https://eso.vse.cz/~novb12/sp1/faq/
https://eso.vse.cz/~novb12/sp1/assets/css/styles.css

1. typograficka chyba - dlouhy text na sirku stranky, zkuste zmensit sirku stranky na max cca 1280px a vycentrovat - **opraveno pro větší čitelnost textu pomocí max-width a margin: auto**
1. zvetsete odkazy v navigaci (padding) - **opraveno pro snazší využití navigace pomocí většího paddingu i fontu**
1. odkazy na externi web by se mely otevrit v nove zalozce - **opraveno pro vyšší uživatelský komfort pomocí target=" _blank"**
1. chyba struktura table - **Mohl byste to, prosím, rozvést? Mám tam hlavičku, tělo i jednotlivé buňky a nevím, co přesně je chybně a nutné k přepracování. Změnila jsem ale zatím velikost písma a u těla změnila tlusté písmo na normální.**
1. pouzivejte `<strong>` misto `<b>` - **opraveno**

**Comment by nvbach91** [comment]
2 - zatim nevidim ze by byl pridan padding
![image](https://user-images.githubusercontent.com/20724910/101295265-de045e00-381c-11eb-9a56-8059db83aaa8.png)
4 - chyba byla tady 
![image](https://user-images.githubusercontent.com/20724910/101295283-f8d6d280-381c-11eb-99f3-4c62831e05f4.png)

**Comment by bnaru** [comment]
- zvetsete odkazy v navigaci (padding) - **opraveno znovu, špatně jsem to pochopila a zvětšovala předtím celou navigaci, nyní už je pro všechna rozlišení u elementu a padding zvětšen**
- chyba struktura table - **nejspíše už předtím opraveno, jelikož mi to už nepíše žádnou chybu (viz. obrázek)**
![image](https://user-images.githubusercontent.com/72208055/101318883-4c6b0f80-3861-11eb-88b2-7e0382972453.png)

**Comment by nvbach91** [comment]
chybi tam `<tr>`, a misto `<div class="main">` pouzivejte `<main>`

**Comment by bnaru** [comment]
- tabulka opravena (<tr> přidáno)
- <div class="main> změněno na <main>

**Comment by bnaru** [comment]
- tabulka opravena (`<tr>` přidáno)
- změna `<div class="main">` na `<main>`

**Comment by nvbach91** [comment]
ok good job
