### ISSUE TITLE
zofm00 - SP1

### ISSUE THREAD

**Issue by Zofak** [nvbach91/4IZ268-2020-2021-ZS#142]
Oprava SP1
![image](https://user-images.githubusercontent.com/72191444/101482401-fbd5de00-3956-11eb-8413-d206ef993e70.png)

Odkazy:
https://eso.vse.cz/~zofm00/SP1/index.html
https://eso.vse.cz/~zofm00/SP1/technika/index.html
https://eso.vse.cz/~zofm00/SP1/kontakty/index.html
https://eso.vse.cz/~zofm00/SP1/vyjezdy/index.html
https://eso.vse.cz/~zofm00/SP1/vyjezdy2020/index.html
https://eso.vse.cz/~zofm00/SP1/styles-index.css

**Comment by nvbach91** [comment]
- nejak vam zmizel favicon
- import vice variant jednoho fontu lze udelat pres jeden odkaz (vyberte z google fonts)
- jinak kdyz pisu jednu chybu tak ona se muze vyskytovat na vice mistech, tak to take muzete opravit, treba to padding u kontaktu, aside, ... by se hodilo pridat

**Comment by Zofak** [comment]
- favicon done
- import pomocí jednoho odkazu done
- padding přidány
