### ISSUE TITLE
prod10-sp1

### ISSUE THREAD

**Issue by david-prochazka** [nvbach91/4IZ268-2020-2021-ZS#148]
https://eso.vse.cz/~prod10/sp1/
https://eso.vse.cz/~prod10/sp1/o-mne/
https://eso.vse.cz/~prod10/sp1/projekty/
https://eso.vse.cz/~prod10/sp1/projekty/akcni-budejcaci/
https://eso.vse.cz/~prod10/sp1/projekty/chaidy/
https://eso.vse.cz/~prod10/sp1/projekty/iphone11/
https://eso.vse.cz/~prod10/sp1/kontakt/

https://eso.vse.cz/~prod10/sp1/assets/css/style.css
https://eso.vse.cz/~prod10/sp1/assets/css/home.css
https://eso.vse.cz/~prod10/sp1/assets/css/pages.css
https://eso.vse.cz/~prod10/sp1/assets/css/about.css
https://eso.vse.cz/~prod10/sp1/assets/css/project.css
https://eso.vse.cz/~prod10/sp1/assets/css/contact.css

https://eso.vse.cz/~prod10/sp1/assets/js/main.js

**Opravil jsem:**
> odkazy na externí weby se nyní otevřou **v nové záložce**

> **optimalizované obrázky** (už v původní verzi jsem optimalizoval, ale je pravda, že se načítali stále pomalu, takže jsem je nyní převedl z PNG do JPG a už je to lepší)

> změna odkazů na stránky a zdroje na **relativní**

**Comment by nvbach91** [comment]
super
