### ISSUE TITLE
prin03-sp1

### ISSUE THREAD

**Issue by nik1488** [nvbach91/4IZ268-2020-2021-ZS#149]

**Comment by nik1488** [comment]
https://eso.vse.cz/~prin03/sp1/index.html
https://eso.vse.cz/~prin03/sp1/ucty.html
https://eso.vse.cz/~prin03/sp1/adresy.html
https://eso.vse.cz/~prin03/sp1/nazory.html
https://eso.vse.cz/~prin03/sp1/konzultace.html

https://eso.vse.cz/~prin03/sp1/css/main.css

1. na 800px width obrazovce nevidim celou navigaci
1. na jeste mensi obrazovce nevidim skoro vubec nevigaci
1. oprave zdeformovane obrazy
1. proc se web jmenuje VSE, je tam neco ohledne skoly? proc tam pisete o zalozeni uctu v Eur? - změnil
1. typograficka chyba - dlouhy text na sirku stranky
1. aktivni navigacni prvek zvyraznete jeste vice - upravil
1. kdyz kliknu na logo, mel bych se dostat na domovskou stranku - udělal odkaz
1. v url stranky maji byt pouze mala pismena - přejmenoval
1. html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky - upravil
1. vsechny obrazky zoptimalizujte
1. nepouzivejte table pro netabulkova data
1. pouzivejte html entity - použil v copywrite
1. konzistentne pouzijte jeden zpusob pojmenovani css trid, doporucuji zapis s pomlckou - upravil
1. chybna syntaxe atributu - nechápu jaký
1. vsechny slozky a soubory prejmenujte aby tam byla mala pismena - přejmenoval

**Comment by nvbach91** [comment]
Nelze provest hodnoceni - web nema zadny styl
![image](https://user-images.githubusercontent.com/20724910/101702864-0f319800-3a82-11eb-91e2-f7378bdac849.png)
9 - neprovedeno
14 - za znakem `=` nema byt mezera

Upozorneni: veskery kod musite nechat zformatovat (napr. ve VSCode Alt+Shift+F)

**Comment by nik1488** [comment]
Už jsem upravil, pardon. Přejmenoval jsem třídu CSS a proto jsem měl problém

**Comment by nik1488** [comment]
14-provedeno
