### ISSUE TITLE
mrkm00-sp1

### ISSUE THREAD

**Issue by michalmrkus** [nvbach91/4IZ268-2020-2021-ZS#150]
Dobrý den, 
zasílám opravu 1.semestrální práce:

https://eso.vse.cz/~mrkm00/sp1/
https://eso.vse.cz/~mrkm00/sp1/cenik/
https://eso.vse.cz/~mrkm00/sp1/vozovy_park/
https://eso.vse.cz/~mrkm00/sp1/o_nas/
https://eso.vse.cz/~mrkm00/sp1/kontakt/

https://eso.vse.cz/~mrkm00/sp1/assets/css/styles.css

1. v odkazech by nemely byt znaky s diakritikou -> opraveno, diakritika odstraněna a místo mezer použito podtržítko
2. odstrante cast 'index.html' z odkazu -> dobře, přepsáno
3. chybi import tucne verze fontu -> importovány dvě verze (klasická a tučná)
4. nevhodna kombinace barvy pozady a barvy textu (kondicni jizdy) -> opraveno na sytě oranžovou barvu
5. odkazum v navigaci pridejte padding tak aby se na ne dale lepe klikat -> opraveno, nyní by mělo jít klikat na celé odkazy, jak v navigaci, tak i níže na mainpage
6. chybna hodnota atributu href emailu -> opraveno, chyběla mi tečka v emailové adrese
7. nevalidni html (vozovy_park) -> opraveno, uváděl jsem u elementu <img> atributy width a height v procenetch místo čísel (validátor v rámci VSC tuto chybu neodhalil, proto jsem musel zvalidovat externě, chybu najít a odstranit)

**Comment by nvbach91** [comment]
2 - myslim odkazy v navigaci Vaseho webu
4 - pekna barva

jinak super

**Comment by michalmrkus** [comment]
Děkuji za zpětnou vazbu, problém číslo 2 by už měl být také opraven.
