### ISSUE TITLE
pfej00-sp1 oprava

### ISSUE THREAD

**Issue by pfej00** [nvbach91/4IZ268-2020-2021-ZS#152]
https://eso.vse.cz/~pfej00/sp1/index.html
https://eso.vse.cz/~pfej00/sp1/home/index.html
https://eso.vse.cz/~pfej00/sp1/galery/index.html
https://eso.vse.cz/~pfej00/sp1/projects/index.html
https://eso.vse.cz/~pfej00/sp1/css/stylesheet.css

Opravil jsem co jsem mohl.

- chybi favicon - OK
- "vsechny dulezite informace nad prehybem"? - nechápu
- neschovavejte menu na vetsich obrazovkach, tam mate dost mista
- stejne tak to zobrazovani navigace nefunguje tak jak ma
- ten efekt pri hoveru na obrazek v galerii bych zrusil .. - OK
- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky odstrante 'index.html' z odkazu - OK
- odstrante cast 'index.html' z odkazu - OK
- vsechny obrazky optimalizujte - OK
- chybi meta informace - OK
- chybna syntaxe pri psani atributu - nevalidni html - mělo by být už OK
- pridejte do title i nazev webu - OK
- opravte pretekani obsahu stranky mimo okna - OK
- nevhodne prizpusobeni pro tisk - bohužel nestíhám dokončit
- sjednotte css soubory do jednoho souboru a umistete ho do slozky css - OK
- odkazy na externi web by se mely otrevrit v nove zalozce - OK

**Comment by nvbach91** [comment]
- pro psani atributu se pouziva znak `"`
- proc tam mate 2x meta tag s `name="title"`, co description a keywords?
