### ISSUE TITLE
zidd00-sp1

### ISSUE THREAD

**Issue by dzidon** [nvbach91/4IZ268-2020-2021-ZS#155]
Oprava:
https://eso.vse.cz/~zidd00/sp1
https://eso.vse.cz/~zidd00/sp1/novinky
https://eso.vse.cz/~zidd00/sp1/interpreti
https://eso.vse.cz/~zidd00/sp1/art
https://eso.vse.cz/~zidd00/sp1/eshop
https://eso.vse.cz/~zidd00/sp1/art/image01
https://eso.vse.cz/~zidd00/sp1/art/image02
https://eso.vse.cz/~zidd00/sp1/art/image03
https://eso.vse.cz/~zidd00/sp1/art/image04
https://eso.vse.cz/~zidd00/sp1/art/image05
https://eso.vse.cz/~zidd00/sp1/eshop/cart

https://eso.vse.cz/~zidd00/sp1/main.css
https://eso.vse.cz/~zidd00/sp1/eshop/eshop.css
https://eso.vse.cz/~zidd00/sp1/interpreti/artists.css
https://eso.vse.cz/~zidd00/sp1/art/art.css

zidd00-assessment.txt:
- odstrante cast 'index.html' z odkazu na stranky - Opraveno
- odstrante pozadi pismen alphabet u interpretu z verze pro tisk - Opraveno
- ja bych do title psal v opacnem poradi tj, nazev stranky pak nazev webu - Opraveno
- velikost fontu pro cteni v odstavci bych dal cca 14 - Opraveno
- pouzijte semanticke tagy, alespon ty zakladni - Opraveno (nav, article, header, footer)

**Comment by nvbach91** [comment]
ok pekny
