### ISSUE TITLE
fral06-sp1

### ISSUE THREAD

**Issue by l-k-sfr-jt** [nvbach91/4IZ268-2020-2021-ZS#156]
- [x] - html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky bez casti 'index.html'
- [x] - pridejte odkaz na hlavni stranku do loga
- [x] - opravte odkaz na HOME v navigaci (nejak jsem se pres nej dostal na eso.vse.cz)
- [x] - zmente font-weight u textu pro cteni (stranka about) na normal
- [x] - nedostatecne prizpusobeni pro tisk
- [x] - opravdu jste sam napsal tech 1000 radku css nebo to byl nejaky framework? - v realu ještě více (cca 1300) -> všechny soubory se styly nalazene ve složce [SCSS](https://eso.vse.cz/~fral06/sp01/assets/sass/main.scss) 
- [x] - chybi meta informace
- [x] - pridejte odkazy na emaily a telefony na strance team
- plus pridana mapa u formulare a strane kontakt

https://eso.vse.cz/~fral06/sp01/
https://eso.vse.cz/~fral06/sp01/o-nas/
https://eso.vse.cz/~fral06/sp01/sluzby/
https://eso.vse.cz/~fral06/sp01/tym/
https://eso.vse.cz/~fral06/sp01/kontakt/
https://eso.vse.cz/~fral06/sp01/assets/css/style.css

**Comment by nvbach91** [comment]
- ta google mapa nefunguje, pouzivejte spis embed feature a odstrante veskery javascript
- telefonni odkaz na telefon v zaklavi webu
- opravte odkaz u loga webu (stranka home)
- u fontu naimportujte pouze verze ktere pouzivate v ramci sveho webu

**Comment by l-k-sfr-jt** [comment]
Děkuji za připomínky.

-  odkaz na telefon v header opraven
- logo opraveno
- odkaz na google fonts optimalizovan
- google mapa fungovala pouze pro delopment, podle js logu, je chyba z důvodu nezaplacení API. Použil jsem tedy[ google iframe](https://developers.google.com/maps/documentation/embed/get-started), děkuji za radu. Mapa již funguje ok
