### ISSUE TITLE
mikt05 - sp1

### ISSUE THREAD

**Issue by tmikula-dev** [nvbach91/4IZ268-2020-2021-ZS#157]
**Zmensete ten velky obrazek get coffee**
- obrázek loga je nyní zmenšený na 250px, takže zabírá menší prostor a stránka je přehlednější
**Typograficka chyba - prilis dlouhy text do sirky stranky**
- typografická chyba byl upravena v css, kde hlavní text o kavárně je omezen max-width: 550px
**Rozsirte levy panel s odkazy na kavarny**
- levý panel byl rozšířen a zároven jednotlivé divy byly zaobaleny do "a", takže se na ně dá lépe klikat
**Zbavte se borderu tech iframu**
- hotovo
**Ta sipka ukazujici nahoru do je dole ma byt interni odkaz na nejaky prvek na strance**
- do headeru bylo přidáno id, na které odkazuje odkaz při kliknutí na šipku
**Nazvy slozek prejmenujte aby byla pouze mala pismena**
- hotovo
**Html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky**
- jednotlivé html kody kaváren byly vloženy do složek odpovídajících, plus byl kompletně předělán systém odkazů. Konec kódu index.html, nyní není v odkazech.
**Pridejte nazev webu i do title (nazev stranky - nazev webu)**
- hotovo
**Pouzivejte ul pro oteviraci dobu**
- ul byl použit pro celou spodní část recenze kavárny, nyní je přehlednější a lépe se s ní může pracovat.
**Pouzivejte html entity**
- html entity byly vhodně použity u znaku copyright a dollaru.
**Pouzivejte semanticke tagy**
- na všech stránkách byly dodělány semantické tagy (header, main, aside, section, footer,...). Kód je teď mnohem přehlednější.
**Naimportujte i tucnou verzi fontu**
- tučná verze textu byla použita u shrnutí recenze, jednotlivé body (cena, lokalita,...) nyní vystupují a celkový dojem je lepší.
**Odstrante pozadi na verzi pro tisk**
- hotovo, odstraněn jak obrázek, tak i záložní barva pozadí
**Odkazy v navigaci rozsirte tak aby se na ne dalo lepe klikat**
- jednotlivé divy jsou zaobaleny do "a" a dá se na ně lépe klikat

- celkové doladění stránky

Odkazy
https://eso.vse.cz/~mikt05/ahoj/home/

https://eso.vse.cz/~mikt05/ahoj/about/
https://eso.vse.cz/~mikt05/ahoj/contact/

https://eso.vse.cz/~mikt05/ahoj/cafe/botanica/
https://eso.vse.cz/~mikt05/ahoj/cafe/cathedral/
https://eso.vse.cz/~mikt05/ahoj/cafe/ema.html
https://eso.vse.cz/~mikt05/ahoj/cafe/hybernska/
https://eso.vse.cz/~mikt05/ahoj/cafe/mazelab/
https://eso.vse.cz/~mikt05/ahoj/cafe/prazirna/
https://eso.vse.cz/~mikt05/ahoj/cafe/spizirna/
https://eso.vse.cz/~mikt05/ahoj/cafe/tramp/
https://eso.vse.cz/~mikt05/ahoj/cafe/venue/
https://eso.vse.cz/~mikt05/ahoj/cafe/vnitroblock/

https://eso.vse.cz/~mikt05/ahoj/assets/css/styles.css

**Comment by nvbach91** [comment]
- odkazy na stranky v tom `aside` by mely byt relativni, tj. pomoci `..`, `.`, a `/`, tj nezacinate od korene webu ale od mista kde se odkaz nachazi
- misto `<b>` byste mel pouzivat `<strong>`
- pripiste "domů" nebo "home" k tomu prvnímu odkazu v navigaci
- domovska stranka nebude `/home`, ale `/`, tj. bez slozky `home`

**Comment by tmikula-dev** [comment]
Dobrý den,
chtěl bych se prosím zeptat, jakým způsobem můžu u těch odkazů odkazovat na prarodiče v mé struktuře stránek, aby byly právě relativní. Protože jsem s tím dost bojoval. Pokud napíši jednu tečku, pohybuji se ve stejné složce, pokud dvě tak jsem v parent složce, ale nevím, jak se můžu dostat z index jedné kavárny ještě o složku nad parent, proto jsem to vyřešil takto, aby to fungovalo. Děkuju za odpověď.
Zbytek doupravím a brzy nahraji.
Děkuju

**Comment by nvbach91** [comment]
priklady viz https://github.com/nvbach91/4IZ268-2020-2021-ZS/wiki/LAB03
`../` znamena jit o jednu slozku nahoru
`../../` znamena jit o dve slozky nahoru, a tak dale

**Comment by tmikula-dev** [comment]
Dobré odpoledne,
do hlavičky jsem tedy připsal slovo "Domů", tag b jsem nahradil tagem strong a domovskou stránku dal nejvýše v mé hierarchii složek (smazal složku home). Vše propojil relativními odkazy a pro stránku home jsem předělal odkazy kompletně, protože se změnilo postavení dokumentu ve struktuře. Vše by mělo být nahrané a funkční.
Díky
