### ISSUE TITLE
kasm13 - sp1

### ISSUE THREAD

**Issue by kasm13** [nvbach91/4IZ268-2020-2021-ZS#158]
- nevhodne zvoleny font pro cteni (spatny import verze fontu) - **hotovo**

- pozadi za textem zkuste snizit pruhlednost - **hotovo**
- do tite bych psal opacne (nazev stranky pak nazev webu) - **hotovo**
- pouzivejte relativni odkazy, jak v html tak i css - **hotovo**
- odstrante 'index.html' z odkazu - **hotovo**
- sjednotte vsechny css soubory do jednoho souboru a zbavte se duplicitnich css pravidel - **x**

https://eso.vse.cz/~kasm13/sp1/uvod/
https://eso.vse.cz/~kasm13/sp1/covid19/
https://eso.vse.cz/~kasm13/sp1/covid_v_cr/
https://eso.vse.cz/~kasm13/sp1/covid_v_cr/1vlna/
https://eso.vse.cz/~kasm13/sp1/covid_v_cr/2vlna/
https://eso.vse.cz/~kasm13/sp1/covid_ve_svete/

https://eso.vse.cz/~kasm13/sp1/styles/styles_uvod.css
https://eso.vse.cz/~kasm13/sp1/styles/styles_covid19.css
https://eso.vse.cz/~kasm13/sp1/styles/styles_covid_v_cr.css
https://eso.vse.cz/~kasm13/sp1/styles/styles_covid_v_cr1.css
https://eso.vse.cz/~kasm13/sp1/styles/styles_covid_v_cr2.css
https://eso.vse.cz/~kasm13/sp1/styles/styles_covid_ve_svete.css

**Comment by nvbach91** [comment]
- obsah v `headline-item title` zmente podle obsahu aktivni polozky v navigaci, tj na strankach covid-19, 1.vlna, 2.vlna, covid ve svete to nebude pokazde `úvod`, navic tady byste mel pouzit `h1`, a ne u prvniho `article`
- chybi import varianty 700 u fontu Open Sans (pro tucne pismo) 
- pridejte meta informace, napr description, keywords

**Comment by kasm13** [comment]
- obsah v headline-item title zmente podle obsahu aktivni polozky v navigaci, tj na strankach covid-19, 1.vlna, 2.vlna, covid ve svete to nebude pokazde úvod, navic tady byste mel pouzit h1, a ne u prvniho article - **hotovo**

- chybi import varianty 700 u fontu Open Sans (pro tucne pismo) - **hotovo**

- pridejte meta informace, napr description, keywords - **hotovo**
