### ISSUE TITLE
beld06-sp1

### ISSUE THREAD

**Issue by Lihodey13** [nvbach91/4IZ268-2020-2021-ZS#160]
https://eso.vse.cz/~beld06/4IZ268/SP1/home/
https://eso.vse.cz/~beld06/4IZ268/SP1/about-us/
https://eso.vse.cz/~beld06/4IZ268/SP1/disasters/
https://eso.vse.cz/~beld06/4IZ268/SP1/learn/
https://eso.vse.cz/~beld06/4IZ268/SP1/form/

https://eso.vse.cz/~beld06/4IZ268/SP1/assets/css/home.css
https://eso.vse.cz/~beld06/4IZ268/SP1/assets/css/about-us.css
https://eso.vse.cz/~beld06/4IZ268/SP1/assets/css/disasters.css
https://eso.vse.cz/~beld06/4IZ268/SP1/assets/css/learn.css
https://eso.vse.cz/~beld06/4IZ268/SP1/assets/css/form.css
https://eso.vse.cz/~beld06/4IZ268/SP1/assets/css/header.css
https://eso.vse.cz/~beld06/4IZ268/SP1/assets/css/footer.css

- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky bez casti 'index.html'  - OK
- k img tagum pridejte atribut width    - OK (ale je prazdny, protoze jsem formatovala img v css)
- chybi import pouziteho fontu   - OK
- odkaz na importovany font nefunguje   - OK
- sjednotte css soubory do jednoho souboru a zbavte se duplicitnich css pravidel  - OK  (pridala jsem 2 css - header.css a footer.css)
- pouzivejte html entity  - OK
- dodrzujte spravnou syntaxi psani html atributu   -  ????
- veskery kod naformatujte  -  OK
- dodrzujte konzistentni zpusob psani neparovch tagu   - OK
- chybi prizpusobeni pro tisk    - NE

**Comment by nvbach91** [comment]
- nevalidni HTML
- chybi import fontu
- duplikovany CSS
- chybi prizpusobeni pro tisk

**Comment by Lihodey13** [comment]
1) nevalidni HTML - opraveno
2) chybi import fontu - opraveno (v header)
3) duplikovany CSS - opraveno
