### ISSUE TITLE
tuma02 - sp1

### ISSUE THREAD

**Issue by AndriiTuma** [nvbach91/4IZ268-2020-2021-ZS#161]
https://eso.vse.cz/~tuma02/sp1/
https://eso.vse.cz/~tuma02/sp1/prodej_kavy/
https://eso.vse.cz/~tuma02/sp1/prodej_kavovary/
https://eso.vse.cz/~tuma02/sp1/contact/
https://eso.vse.cz/~tuma02/sp1/servis/
https://eso.vse.cz/~tuma02/sp1/assets/css/main.css

[tuma-assessment.txt](https://github.com/nvbach91/4IZ268-2020-2021-ZS/files/5683737/tuma-assessment.txt)

1. opravte odkazy na stranky - bez casti 'index.html' -- opraveno
1. navigacni prvky zvetsete aby se na ne dalo lepe klikat -- opraveno
1. pouzivejte nejaky vhodnejsi font -- opraveno na font 'Roboto', sans-serif
1. odstrante podtzeni odkazu v navigaci -- opraveno
1. vyraznejsi zpusobem zvyraznete aktivni polozku v navigaci -- opraveno
1. zmensete sirku textoveho odstavce - typograficka chyba -- opraveno
1. pouzivejte emailovy a telefonni odkaz -- opraveno
1. na verzi pro tisk schovejte pozadi (stranka kontakt) -- opraveno
1. na verzi pro tisk upravte layout produktu na max 3 produkty na jendom radku -- opraveno
1. parametry produktu zarovnejte doleva a na to pouzivejte <div> a ne <table> -- opraveno ale s table
1. do title bych psal nejprve nazev stranky a pak nazev webu -- opraveno
1. pridejte padding do footeru -- opraveno
1. pouzivejte semanticky tag <main> -- opraveno
1. pouzivejte pouze jeden zpusob pojmenovani atributu class a id - nejlepe zapis s malymi pismeny a s pomlckou -- opraveno
1. odkazy na externi web by se mely otevrit v nove zalozce -- opraveno

**Comment by nvbach91** [comment]
2 - musite zvetsit primo element `<a>` aby se na to dalo lepe klikat
3 - chybi import fontu roboto
6 - odstavce na strance servis je stale siroky
12 - padding by mel byt pridat nahore i dole
13 - tag `<footer>` by mel byt mimo tagu `<main>`

**Comment by AndriiTuma** [comment]
https://eso.vse.cz/~tuma02/sp1/
https://eso.vse.cz/~tuma02/sp1/prodej_kavy/
https://eso.vse.cz/~tuma02/sp1/prodej_kavovary/
https://eso.vse.cz/~tuma02/sp1/contact/
https://eso.vse.cz/~tuma02/sp1/servis/
https://eso.vse.cz/~tuma02/sp1/assets/css/main.css

2 - musite zvetsit primo element <a> aby se na to dalo lepe klikat -- ? Neopraveno
3 - chybi import fontu roboto -- opraveno
6 - odstavce na strance servis je stale siroky -- opraveno
12 - padding by mel byt pridat nahore i dole -- opraveno
13 - tag <footer> by mel byt mimo tagu <main> -- opraveno
