### ISSUE TITLE
kozo01 - sp1 

### ISSUE THREAD

**Issue by oli711** [nvbach91/4IZ268-2020-2021-ZS#162]
- html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte  - opraveno
odkazy na stranky bez casti 'index.html' - opraveno
- nevalidni html - opraveno
- neparovy tag piseme bez s '>' a ne s '/>' na konci - opraveno
- pouzivejte html entity - opraveno 
- chybi meta informace - opraveno
- odstrante importovane fonty, ktere nejsou pouzite - opraveno
- fonty importujte v html pomoci <link> - opraveno
- na nekterych strankach nejsou pouzity fonty - opraveno 
- sjednotte css soubory do jednoho souboru a zbavte se duplicitnich css pravidel - vsechno je ve slozce css
- veskery kod naformatujte - opraveno
- nerozumim proc se stranky oteviraji pokazde v nove zalozce opraveno 
- chybi favicon na strance about - opraveno
- opravte pretekani obsahu stranky na male obrazovce - opraveno
- opravte zdeformovane obrazky - opraveno
- pridejte odkaz na hlavni stranku do loga - opraveno
- odstrante pozadi na verzi pro tisk - opraveno 
- nekonzistentni zapati - opraveno 

https://eso.vse.cz/~kozo01/sp1/homepage/
https://eso.vse.cz/~kozo01/sp1/about/
https://eso.vse.cz/~kozo01/sp1/service/
https://eso.vse.cz/~kozo01/sp1/team/
https://eso.vse.cz/~kozo01/sp1/contact/
https://eso.vse.cz/~kozo01/sp1/css/style.ccs
https://eso.vse.cz/~kozo01/sp1/css/rtl.css
https://eso.vse.cz/~kozo01/sp1/css/responsive.css
https://eso.vse.cz/~kozo01/sp1/js/main.js

**Comment by nvbach91** [comment]
1. domovska stranka ma mit odkaz `/`
1. vsechny odkazy na stranky  about service team contact nefunguji
1. web nepouziva clean url
1. v SP1 nelze pouzit javascript
1. v SP1 nelze pouzit cizi knihovny (bootstrap, themes, jquery, ...)
1. u google mapy pouzijte funkci embed

**Comment by oli711** [comment]
https://eso.vse.cz/~kozo01/sp1/homepage/
 https://eso.vse.cz/~kozo01/sp1/about/
 https://eso.vse.cz/~kozo01/sp1/services/
 https://eso.vse.cz/~kozo01/sp1/team/
 https://eso.vse.cz/~kozo01/sp1/contact/
 https://eso.vse.cz/~kozo01/sp1/assets/css/style.css

Opraveno

**Comment by oli711** [comment]
Jestli se nemýlím tak ted' všechny odkazy fungují, web používá clean url, taky odstranila jsem všechno, co tam nemuselo být

**Comment by nvbach91** [comment]
- odstrante cast 'index.html' z odkazu v navigaci
- soubor pro domovskou stranku vyndejte z slozky `home`
- pridejte atribut "lang"
- opravte nazev meta keywords
- naimportujte verze font-weight ktere pouzivate
- pridejte fallback font
- zvalidujte HTML...
- pouzivejte semanticke tagy (`<main>`, `<header>`, atd.)
- pouzivejte emailove a telefonni odkazy
- odstrante veskery javascript
- odstrante veskery inline CSS
- odstrante ten blinkr u loga webu
- pouzivejte smysluplny obsah, ne lorem ipsum
- opravte zdeformovane obrazky
- chybi zvyrazneni aktivni polozky v navigaci

mate posledni pokus

**Comment by oli711** [comment]
Díky za poslední pokus
odstrante cast 'index.html' z odkazu v navigaci - odstranila jsem
soubor pro domovskou stranku vyndejte z slozky home - ted' jsou tam dvě možnosti, přes / a taky /homepage
pridejte atribut "lang" - přidala jsem 
opravte nazev meta keywords - opraveno
naimportujte verze font-weight ktere pouzivate - opraveno..?
pridejte fallback font - opraveno
zvalidujte HTML...- zvalidovan 
pouzivejte semanticke tagy (<main>, <header>, atd.) - přidan main, header 
pouzivejte emailove a telefonni odkazy - opraveno
odstrante veskery javascript - opraveno
odstrante veskery inline CSS - 
odstrante ten blinkr u loga webu - ted nebliká, jen svití 
pouzivejte smysluplny obsah, ne lorem ipsum - opraveno
opravte zdeformovane obrazky - opraveno 
chybi zvyrazneni aktivni polozky v navigaci - přidala jsem 

https://eso.vse.cz/~kozo01/sp1/
https://eso.vse.cz/~kozo01/sp1/homepage/
https://eso.vse.cz/~kozo01/sp1/about/
https://eso.vse.cz/~kozo01/sp1/services/
https://eso.vse.cz/~kozo01/sp1/team/
https://eso.vse.cz/~kozo01/sp1/contact/ 
https://eso.vse.cz/~kozo01/sp1/assets/css/style.css

Doufám, že ted už je lepší.. 
@nvbach91
