### ISSUE TITLE
mala12 - sp1

### ISSUE THREAD

**Issue by alexmalychu** [nvbach91/4IZ268-2020-2021-ZS#163]
Dobrý den. Posílám opravenou první SP.

https://eso.vse.cz/~mala12/sp1/main-page/
https://eso.vse.cz/~mala12/sp1/rules/
https://eso.vse.cz/~mala12/sp1/characters/
https://eso.vse.cz/~mala12/sp1/dungeon-master/
https://eso.vse.cz/~mala12/sp1/race/
https://eso.vse.cz/~mala12/sp1/skills/
https://eso.vse.cz/~mala12/sp1/profession/
https://eso.vse.cz/~mala12/sp1/materials/
https://eso.vse.cz/~mala12/sp1/dragon-lair-online/

1. Favicon a font
2. Zarovnání obrázků na stránce Povolání
3. Typografie - délka textu na řádku
4. Absence tagů <header> a <footer>
5. Přejmenování html souborů a vložení do složek
6. Verze k tisku - pozadí a navigace
7. Identifikace stránky - logo (Mám všude nahoře stejný obrázek s názvem DrD)
8. Zvýraznění aktivní položky navigace - nefunguje, zkoušel jsem různými způsoby

Mohl byste mi, prosím, poradit s tou navigací? Mimo soutěž - jen mě zajímá, proč mi to nefunguje.

**Comment by nvbach91** [comment]
1 - "16 px" neni validni CSS hodnota, z google fonts importujte font weight 400 a 700, nikoliv jen 100
3 - pridejte line-height aby radky nebyly tak blizko sebe
5 - hlavní stránku dejte mimo složek jako jediná, z odkazu URL v navigaci odstrante cast 'index.html'
6 - na verzi pro tisk zmente barvu pismene aby to bylo citelne
8 - vytvorite CSS pravidlo `.active { background-color: red } ` a v souboru se strankou `pravidla` pridejte CSS tridu `active` k navigacnimu prvku `pravidla`, v souboru se strankou `rasy` pridejte CSS tridu `active`  k navigacnimu prvku `rasy`, to same udelejte pro vsechny jine stranky

- dale opravte pretekani obsahu stranky z sirky okna (viewportu)

![image](https://user-images.githubusercontent.com/20724910/102026229-e91b3900-3d9c-11eb-8fdc-830ffc2626ea.png)
