### ISSUE TITLE
kyvt00 - sp1

### ISSUE THREAD

**Issue by kyvt** [nvbach91/4IZ268-2020-2021-ZS#164]
1. chybi identifikace webu (nazev webu, logo, banner, atd.) - Opraveno
1. chybi import tucne verze fontu - Opraveno
1. vsechny obrazky optimalizujte - Opraveno
1. sjednotte css soubory do jednoho souboru a zbavte se duplicitnich css pravidel - Opraveno
1. chybi prizpusobeni pro tisk - Netuším
1. pro nazvy css trid a id pouzivejte anglictinu.. - Opraveno
1. typograficka chyba - prilis dlouhy text na sirku stranky 
1. pouzivejte html entity - Opraveno
1. img tagum pridejte atribut width - Opraveno
1. nevalidni html (v miste kde mate seznamy) - Netuším 
1. html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky a odstrante 'index.html' z odkazu - Nevím, jak dát pryč index.html

https://eso.vse.cz/~kyvt00/sp1/kontakt/
https://eso.vse.cz/~kyvt00/sp1/kariera/
https://eso.vse.cz/~kyvt00/sp1/akce/
https://eso.vse.cz/~kyvt00/sp1/vyzkum/
https://eso.vse.cz/~kyvt00/sp1/oNas/
http://eso.vse.cz/~kyvt00/sp1/css/Header-Footer.css
http://eso.vse.cz/~kyvt00/sp1/css/index.css
http://eso.vse.cz/~kyvt00/sp1/css/vyzkum.css
http://eso.vse.cz/~kyvt00/sp1/css/kariera.css
http://eso.vse.cz/~kyvt00/sp1/css/akce.css
http://eso.vse.cz/~kyvt00/sp1/css/kontakt.css

**Comment by nvbach91** [comment]
2 - stale chybi import variant 400 a 700 fontu, znovu zajdete na google fonts a vyberte tyto varianty pro import
4 - stale vidim 6 css souboru - v tuto chvili je jednodussi a praktictejsi je sjednotit do jednoho souboru, CSS kod naformatujte
5 - tisk se implementuje pomoci media query `@media print {  }`
7 - 
![image](https://user-images.githubusercontent.com/20724910/102026991-942df180-3da1-11eb-884e-2e45758a0e41.png)
9 - myslel jsem atribut napr. `width="200"`, a ne inline CSS - opravte
10 - tady je to nevalidni, opravte
![image](https://user-images.githubusercontent.com/20724910/102027023-c3446300-3da1-11eb-8081-49772effab38.png)
11 - takhle to myslim
![image](https://user-images.githubusercontent.com/20724910/102027034-e1aa5e80-3da1-11eb-8760-d365846ede1b.png)
