### ISSUE TITLE
posn01 - SP1

### ISSUE THREAD

**Issue by NikolPP** [nvbach91/4IZ268-2020-2021-ZS#165]
https://eso.vse.cz/~posn01/SP1/mainpage/index.html
https://eso.vse.cz/~posn01/SP1/about/index.html
https://eso.vse.cz/~posn01/SP1/recipes/index.html
https://eso.vse.cz/~posn01/SP1/blog/index.html
https://eso.vse.cz/~posn01/SP1/galerie/index.html
https://eso.vse.cz/~posn01/SP1/mainpage/mainpage.css
https://eso.vse.cz/~posn01/SP1/about/about.css
https://eso.vse.cz/~posn01/SP1/recipes/recipes.css
https://eso.vse.cz/~posn01/SP1/blog/blog.css
https://eso.vse.cz/~posn01/SP1/galerie/galerie.css

Opraveno

**Comment by nvbach91** [comment]
1. web nesplnuje podminku smysluplneho obsahu
1. duplikovani CSS pravidel napric vice soubory
1. nevalidni CSS, kod neni formatovany
1. kod neni naformatovany (CSS i HTML)
1. chybna syntaxe pro psani atributu v HTML
1. nevalidni HTML
1. nekonzistentni zpusob psani atributu class
1. h-tagy se nepouziva v navigaci
1. chybi favicon
1. poradi navigacnich prvku by melo zustat stejny napric strankami
1. nevhodne pouzivani fontu - prilis mnoho fontu, misty font neni aplikovan
1. odkaz "nahoru" ma byt navigace pomoci atributu id a ne odkaz na stejnou stranku
1. hodnota "Muj web" neni vhodny pro meta description
1. odstrante veskery inline CSS z HTML
1. z URL odkazu v navigaci odstrante cast "index.html"

**Comment by NikolPP** [comment]
https://eso.vse.cz/~posn01/sp1/mainpage/
https://eso.vse.cz/~posn01/sp1/about/
https://eso.vse.cz/~posn01/sp1/blog/
https://eso.vse.cz/~posn01/sp1/galerie/
https://eso.vse.cz/~posn01/sp1/recipes/
https://eso.vse.cz/~posn01/sp1/mainpage/mainpage.css
https://eso.vse.cz/~posn01/sp1/about/about.css
https://eso.vse.cz/~posn01/sp1/blog/blog.css
https://eso.vse.cz/~posn01/sp1/galerie/galerie.css
https://eso.vse.cz/~posn01/sp1/recipes/recipes.css

**Comment by nvbach91** [comment]
@NikolPP k tomu prosím napište seznam chyb z minulé verze vč. kde co jste (ne)opravila + vysvětlení, proč jste to (ne)opravila a případně nejasnosti

**Comment by NikolPP** [comment]
web nesplnuje podminku smysluplneho obsahu - **opraveno** 
duplikovani CSS pravidel napric vice soubory (nepochopila jsem, co je špatně)
nevalidni CSS, kod neni formatovany- **opraveno** 
kod neni naformatovany (CSS i HTML)- **opraveno** 
chybna syntaxe pro psani atributu v HTML (nenašla jsem konkrétní chyby)
nevalidni HTML- **opraveno** 
nekonzistentni zpusob psani atributu class
h-tagy se nepouziva v navigaci- **opraveno** 
chybi favicon- **opraveno** 
poradi navigacnich prvku by melo zustat stejny napric strankami- **opraveno** 
nevhodne pouzivani fontu - prilis mnoho fontu, misty font neni aplikovan- **opraveno** 
odkaz "nahoru" ma byt navigace pomoci atributu id a ne odkaz na stejnou stranku- **opraveno** 
hodnota "Muj web" neni vhodny pro meta description- **opraveno** 
odstrante veskery inline CSS z HTML- **opraveno** 
z URL odkazu v navigaci odstrante cast "index.html"

**Comment by nvbach91** [comment]
- duplikovani CSS pravidel napric vice soubory - mate pro kazdou stranku jeden plnohodnotny soubor a opakuji se v nich CSS pravidla, je potreba je sjednotit do jednoho souboru a zbavit se duplicitnich pravidel
- kdyz piseme nejaky atribut v html, pouzivame uvozovky
- obcas pouzivate podrtzitko, obcas pouzivate pomlcku v nazvech atributu class, pouzivejte pouzej jedno z nich
- stale mate inline css
- 'index.html' napr.: 
![image](https://user-images.githubusercontent.com/20724910/102690892-de332f00-4208-11eb-9e36-75a624736c07.png)
- font neni konzistentni v ramci webu
- nespravna hodnota atributu `lang`
