### ISSUE TITLE
ngut37-sp1

### ISSUE THREAD

**Issue by ngut37** [nvbach91/4IZ268-2020-2021-ZS#166]
### Odkazy
https://eso.vse.cz/~ngut37/sp1
https://eso.vse.cz/~ngut37/sp1/services
https://eso.vse.cz/~ngut37/sp1/gallery
https://eso.vse.cz/~ngut37/sp1/about
https://eso.vse.cz/~ngut37/sp1/contacts
https://eso.vse.cz/~ngut37/sp1/assets/css/main.css

### Poznamky
1. _html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky bez casti 'index.html'_ - **opraveno**
2. _chybi zvyrazneni aktivni polozky navigace_ - **opraveno** (font color a undelined)
3. _opravte pretekani obsahu stranky z viewportu na sirku_ - **opraveno**
4. _chybi 1 stranka (ma jich byt 5), pridejte treba stranku s referenci_ - **opraveno** (stranka `About` rozdelena na `About` a `Contacts`)
5. _vsechny obrazky zoptimalizujte_ - **opraveno**
6. _opravte umisteni obrazku na strance about_ - **opraveno**
7. _pouzivejte nejaky web font napr open sans nebo roboto_ - **opraveno** (pouzito Open Sans)
8. _pouzivejte html entity_ - **opraveno** (misto © -> `&copy;` a & -> `&amp;`)
9. _chybi prizpusobeni pro tisk_ - **opraveno** (pridano na konec `main.css`)

- pridana emebedded mapa v kontaktech (bohuzel odkazuje jen na Sapu, protoze podnik neni zaznamenan v google)

**Comment by nvbach91** [comment]
7 - znovu zajdete na google fonts a vyberte varianty fontu, ktere pouzivate na svem webu (400 a 700)
9 - na verzi pro tisk opravte barvu pismene tak aby se to dalo precist, dale take odstrante ty stiny
10 - odkazy na externi web by se mely otevrit v nove zalozce
11 - `box-sizing: border-box` se dava do `*`, `font-family` do `body`, atd..

**Comment by ngut37** [comment]
### Review round 2
7. _znovu zajdete na google fonts a vyberte varianty fontu, ktere pouzivate na svem webu (400 a 700)_ - **opraveno** (added `:wght@400;700`)
9. _na verzi pro tisk opravte barvu pismene tak aby se to dalo precist, dale take odstrante ty stiny_ - **opraveno** (`color: black` a `box-shadow: none`
10. _odkazy na externi web by se mely otevrit v nove zalozce_ - **opraveno** (odkazy na soc. media na strance Contacts)
11. _box-sizing: border-box se dava do *, font-family do body, atd._ - **opraveno** (nevim jiste, zda v poradku)
