### ISSUE TITLE
klep03 - SP1

### ISSUE THREAD

**Issue by petr-klepetko** [nvbach91/4IZ268-2020-2021-ZS#167]
1. to zahlavi jak je tak velky neni vhodny davat jako fixed prvek, tak bud to zmensete nebo nechte normalne do scrollovani
            - opraveno, už to není fixed prvek a scroluje se dolů
1. neimportovany font - zapomněl jsem na to, v css to bylo ale připravené, přidal jsem tam linky s importy
1. pouzivejte telefonni odkaz - opraveno
1. pouzivejte html entity - nahradil jsem copyright, nejsem si jistý, jestli jsem našel všechno
1. zmensete obrazky na verzi pro tisk - bohužel nestíhám, nechci riskovat, že si tam něco rozbiju
1. sjednotte soubory css a zbavte se duplicitninch css pravidel - Nezbyl mi na to čas, kdybych to měnil, tak to chci 100% otestovat, bojím se, že bych si tam něco rozbil

Soubory:
https://eso.vse.cz/~klep03/sp1/
https://eso.vse.cz/~klep03/sp1/novinky/
https://eso.vse.cz/~klep03/sp1/akce/
https://eso.vse.cz/~klep03/sp1/o_nas/
https://eso.vse.cz/~klep03/sp1/kontakty/

http://eso.vse.cz/~klep03/sp1/css/main.css
http://eso.vse.cz/~klep03/sp1/css/print.css

**Comment by nvbach91** [comment]
ty importy fontu je lepsi delat v `<link>`

**Comment by petr-klepetko** [comment]
Já to udělal, abych nemusel měnit všechny html soubory, ale mohl udělat jednu centrální změnu v css. A v čem je to prosím lepší?

**Comment by nvbach91** [comment]
je to preferovany zpusob protoze Google Fonts  serviruje fonty dynamickym zpusobem (neodkazuje na staticky soubor) a take napr. z duvodu performance pri nacitani fontu (stazeni toho fontu je v pripade @import zanechan az po stazeni celeho vaseho css souboru, v pripade `<link>` je to nezavisle), a muze se stat ze na nekterych platformach se vam ten font rozbije pri @import
