### ISSUE TITLE
fouf00 - sp1

### ISSUE THREAD

**Issue by Foky09** [nvbach91/4IZ268-2020-2021-ZS#168]
https://eso.vse.cz/~fouf00/sp1/index.html
https://eso.vse.cz/~fouf00/sp1/jidelnilistek/index.html
https://eso.vse.cz/~fouf00/sp1/napojovylistek/index.html
https://eso.vse.cz/~fouf00/sp1/fotogalerie/index.html
https://eso.vse.cz/~fouf00/sp1/onas/index.html

https://eso.vse.cz/~fouf00/sp1/css/styles.css

1. odkazy v navigaci rozsirte tak aby slo na ne lepe klikat **opraveno**
1.  obrazky optimalizujte **opraveno**
1.  jidelni menu by nemelo byt takhle siroke, pridejte tam max-width **opraveno**
1.  misto toho odkazu s tou mapou pridejte iframe z google maps s vyznacenym mistem na mape **opraveno**
1.  opravte footer **nevím, co přesně**
1.  chybi meta informace **opraveno**
1.  prizpusobeni pro tisk nefunguje **opraveno**
1.  pouzivejte telefonni a emailove odkazy **opraveno**
1.  pridejte padding tomu formulari **formulář měl padding již předtím**
1.  opravte pretekani obsahu stranky do sirky **nevím, co přesně**
1.  vyraznejsim zpusobem zvyraznete aktivni polozku v navigaci **opraveno**
1.  v navigaci pridejte odkaz na hlavni stranku **celá horní lišta slouží jako odkaz na hlavní stránku**
1.  pouzijte nejaky web font, napr open sans nebo roboto pro cteni mimo jidelniho menu **opraveno**
1.  k tem inputum ve formulari pridejte prislusny type (email, date) **opraveno**

**Comment by nvbach91** [comment]
5 - napr horni a dolni padding 
7 - zkuste doladit perfektne tisk alespon stranky menu 
9 - to je porad malo paddingu, dejte tam treba 25px
10 - tady nema byt ten scroll bar doprava
![image](https://user-images.githubusercontent.com/20724910/102027447-71e9a300-3da4-11eb-8af1-7a729c7f6ddf.png)
12 - myslim ze ne vsechny to napadne na to klikat
13 - chybi import web fontu Roboto Condensed

**Comment by Foky09** [comment]
Dobrý den, 
děkuji za připomínky, mělo by to být vše již opraveno.

5 - přidán padding
7 - je nastavena větší šířka pro menu při tisku
9 - přidán větší padding
10 - snad už by mělo být opraveno, alespoň mně se to již nezobrazuje
12 - přidán odkaz do navigace
13 - opraveno
