### ISSUE TITLE
ayur00 - SP1

### ISSUE THREAD

**Issue by rasulyao** [nvbach91/4IZ268-2020-2021-ZS#169]
1. chybi favicon -      ok 
1. chybi zvyrazneni aktivni polozky navigace    -      ok 
1. nevhodna kombinace pozadi a textu         -       ok
1. pridejte odkaz na hlavni stranku do loga webu   -  ok
1. do title pridejte nazev webu           -        ok                                        
1. html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, 
podle toho take opravte odkazy na stranky bez casti 'index.html'   - ok
1. vsechny nazvy souboru maji byt malymi pismeny   -  ok
1. nevalidni html                -                   ok
1. atribut alt nema mit prazdnou hodnotu        -    ok
1. pouzivejte html entity            -               ok
1. chybi meta informace                 -           ok
1. veskery kod naformatujte               -          ok
1. vsechny obrazky zoptimalizujte            -       50/50(nepochopil jsem)
1. stranka about us nema zadnou dalsi informaci 
1. web neni responzivni   
1. chybi prizpusobeni pro tisk      
1. nevhodny font pro web  

https://eso.vse.cz/~ayur00/sp01/home/
https://eso.vse.cz/~ayur00/sp01/seznam-jazyku/
https://eso.vse.cz/~ayur00/sp01/seznam-ucitelu/
https://eso.vse.cz/~ayur00/sp01/about-us/
https://eso.vse.cz/~ayur00/sp01/about-founder/

https://eso.vse.cz/~ayur00/sp01/assets/css/style.css

Mám ještě ty 4 chyby na které srdečně prosím ještě čas abych vyřešil všechno.

**Comment by nvbach91** [comment]
6 - jenom domovskou stranku dejte mimo slozky `home`, a smazte slozku `home`
10 - na tohle zrovna neni dobry pouzivat html entity, pouzivejte normalni cesky text
![image](https://user-images.githubusercontent.com/20724910/102027556-40250c00-3da5-11eb-983d-c508f408697f.png)
11 - pridejte jeste meta keywords
13 - optimalizace = zmenseni obrazku na vhodny rozmer a komprese

**Comment by rasulyao** [comment]
pridejte jeste meta keywords  -  ok
vsechny obrazky zoptimalizujte  -  ok 
jenom domovskou stranku dejte mimo slozky home, a smazte slozku home  -  ok
nevhodny font pro web  -  ok
stranka about us nema zadnou dalsi informaci  -  ok
web neni responzivni  -  ok
chybi prizpusobeni pro tisk  -  no
 

https://eso.vse.cz/~ayur00/sp01/
https://eso.vse.cz/~ayur00/sp01/seznam-jazyku/
https://eso.vse.cz/~ayur00/sp01/seznam-ucitelu/
https://eso.vse.cz/~ayur00/sp01/about-us/
https://eso.vse.cz/~ayur00/sp01/about-founder/
