### ISSUE TITLE
bora13 - SP1

### ISSUE THREAD

**Issue by andreaborekova** [nvbach91/4IZ268-2020-2021-ZS#170]
https://eso.vse.cz/~bora13/sp1/index.html
https://eso.vse.cz/~bora13/sp1/aboutme.html
https://eso.vse.cz/~bora13/sp1/pricing.html
https://eso.vse.cz/~bora13/sp1/contact.html
https://eso.vse.cz/~bora13/sp1/nutrition.html
https://eso.vse.cz/~bora13/sp1/training.html
https://eso.vse.cz/~bora13/sp1/assets/styles.css

1. odkazy na interni web by se mely otevrit ve stejne zalozce
1. pouzivejte nejaky font vhodny pro cteni v pasazich textu - **OPRAVENE**
1. vyraznejsim zpusobem/barvou zvyraznete aktivni polozku v navigaci - **OPRAVENE**
1. sjednotte css soubory do jednoho souboru a zbavte se duplicitnich css pravidel - **OPRAVENE**
1. css soubor premistete do slozky /css
1. html soubory prejmenujte na index.html a dejte je do slozek s nazvy ktere odpovidaji nazvu stranky, podle toho take opravte odkazy na stranky bez casti 'index.html'
1. chybi import tucne verze fontu - **OPRAVENE**
1. veskery kod naformatujte - **OPRAVENE**
1. opravte verze pro tisk
1. pouzivejte semanticke tagy - **OPRAVENE**
1. pouzivejte html entity - **OPRAVENE**
1. oprave pretekani textu z cointaineru na male obrazovce - **OPRAVENE**
1. web neni responzivni - **Z CASTI OPRAVENE**

**Comment by nvbach91** [comment]
2 - dejte tam nejaky bezpatkovy font jako Roboto nebo Open Sans
7 - znovu zajdete na google fonts, najdete fonty ktere chcete pouzit, zaskrtnete font weighty, ktere chcete pouzivat (400 a 700) a znovu naimportujte pres jeden tag `<link>`
8 - CSS kod naformatujte
14 - nevalidni HTML - zkontrolujte
15 - na ty obrazky nepouzivejte tag `<article>`
16 - `<footer>` vyndejte z `<main>`

**Comment by andreaborekova** [comment]
https://eso.vse.cz/~bora13/sp1/index.html
https://eso.vse.cz/~bora13/sp1/aboutme.html
https://eso.vse.cz/~bora13/sp1/pricing.html
https://eso.vse.cz/~bora13/sp1/contact.html
https://eso.vse.cz/~bora13/sp1/nutrition.html
https://eso.vse.cz/~bora13/sp1/training.html
https://eso.vse.cz/~bora13/sp1/assets/styles.css

2 - dejte tam nejaky bezpatkovy font jako Roboto nebo Open Sans **-opravene**
7 - znovu zajdete na google fonts, najdete fonty ktere chcete pouzit, zaskrtnete font weighty, ktere chcete pouzivat (400 a 700) a znovu naimportujte pres jeden tag <link> **-opravene**
8 - CSS kod naformatujte **-opravene**
14 - nevalidni HTML - zkontrolujte **-opravene**
15 - na ty obrazky nepouzivejte tag <article> **-opravene**
16 - <footer> vyndejte z <main> **-opravene**
