### ISSUE TITLE
dinv00-sp2-proposal

### ISSUE THREAD

**Issue by dinv00** [nvbach91/4IZ268-2020-2021-ZS#172]
Dobrý den,

v tabulce stavů schválení SP2 mám u svého xname status: N/A. Návrh jsem ale určitě včas odevzdával a tak se chci zeptat jestli vám mám návrh poslat znova přes Google Forms, popřípadě jestli by jste znovu nezkontroloval zdali vám můj návrh přišel.

Děkuji.

**Comment by nvbach91** [comment]
Zkontroloval jsem a není to tam

**Comment by dinv00** [comment]
Dobře, odevzdal jsem znovu.

**Comment by nvbach91** [comment]
ok
