### ISSUE TITLE
SP2 repozitář

### ISSUE THREAD

**Issue by dmitrijt9** [nvbach91/4IZ268-2020-2021-ZS#173]
@nvbach91 Dobrý den :)

Chtěl bych se zeptat kdy a jak se mi zpřístupní repozitář na githubu pro druhou semestrálku? Návrh na zadání jsem už před nějakou dobou odevzdal :)

Nebo si mám založit vlastní? 

Díky.

**Comment by nvbach91** [comment]
Všichni to už mají dávno. Musíte přijmout pozvánku do repozitáře https://github.com/nvbach91/4IZ268-2020-2021-ZS/invitations

**Comment by dmitrijt9** [comment]
bohužel mi nepřišlo nikam žádné upozornění, až tedˇ :) 
Díky jsem tam 👌
