### ISSUE TITLE
pryp00 - SP1

### ISSUE THREAD

**Issue by UnrealNeriel** [nvbach91/4IZ268-2020-2021-ZS#175]
odevzdávám 1. semestrální práci s malým opožděním.
https://eso.vse.cz/~pryp00/sp1/
https://eso.vse.cz/~pryp00/sp1/products/
https://eso.vse.cz/~pryp00/sp1/career/
https://eso.vse.cz/~pryp00/sp1/contact/
https://eso.vse.cz/~pryp00/sp1/about-us/
https://eso.vse.cz/~pryp00/sp1/main.css

**Comment by nvbach91** [comment]
1. pouzivani absolutnich odkazu
2. font neni spravne importovany (chybi bold)
3. nevalidni HTML
4. prazdny atribut alt
5. nevhodne udelane efekty pri mouse hover
6. prilis pozdni odevzdani (termin byl do 22.11)

**Comment by UnrealNeriel** [comment]
1. pouzivani absolutnich odkazu - ok
2. font neni spravne importovany (chybi bold) - ok
3. nevalidni HTML - ok
4. prazdny atribut alt - ok
5. nevhodne udelane efekty pri mouse hover - ok
6. prilis pozdni odevzdani (termin byl do 22.11) - not ok
