### ISSUE TITLE
SP2 - neproveditelnost zadání

### ISSUE THREAD

**Issue by dmitrijt9** [nvbach91/4IZ268-2020-2021-ZS#234]
@nvbach91 Zdravím,

bohužel jsem si neprostudoval dostatečně detailně API od Spotify předtím než jsem odevzdal zadání a teď jsem zjistil, že to není tak úplně proveditelné.
Nedostanu se ke zdroji audio souboru ani kdybych se tam přihlásil pomocí svého premium účtu. Bez zdroje audio souboru nejsem schopný udělat jeho vizualizaci a export do videa.

Nevadí, když ještě změním zadání? Budu muset vymyslet nějakou jinou aplikaci.

P.S. Nemáte nějaké nápady ještě? :) 

Díky

**Comment by nvbach91** [comment]
to vytvareni videi muzete dropnout, bude stacit kdybyste udelal autentizaci vuci spotify a ui pro vyhledavani skladeb a jejich prehravani s moznosti ukladani pro rychly pristup

**Comment by dmitrijt9** [comment]
Tak me napadlo udelat neco podobnyho co navrhujete, akorat s knihama a pouzival bych Google Books API https://developers.google.com/books/docs/overview

Ve zkratce by tam bylo vyhledavani knih, ukladani do svych policek, popripade vytvareni novych policek.
Jeste ale samozrejme muzu vytvorit detailnejsi zadani jako predtim :) 

@nvbach91 Je to takhle v poradku? Diky :)

**Comment by nvbach91** [comment]
bud knihy, ale s tim ze pouzijete OAuth a moznost pouzivani aplikace vice uzivately ve stejnem prohlizeci podle toho, kdo je zrovna prihlaseny

nebo zustante u pisnicek ze Spotify

**Comment by dmitrijt9** [comment]
delam nakonec knihy i s google oauth2 :)

diky
