### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by goonerknight** [nvbach91/4IZ268-2020-2021-ZS#26]
![image](https://user-images.githubusercontent.com/72233414/99059839-66d20600-259f-11eb-9b17-dacf832d0f48.png)

Nedovolí mi to uploadovat žádné soubory. Můžete mi prosím poradit?

Děkuji

**Comment by nvbach91** [comment]
viz https://github.com/nvbach91/4IZ268-2020-2021-ZS/issues/1#issuecomment-723449328
