### ISSUE TITLE
Dva vykřičníky u DCV

### ISSUE THREAD

**Issue by Zofak** [nvbach91/4IZ268-2020-2021-ZS#3]
Zdravím, 
kód prošel jak na webu, tak v aplikaci bez chyb a warningů. Mohu se tedy zeptat, za co ty dva vykřičníky?

Děkuji.

https://eso.vse.cz/~zofm00/cv03/index.html
https://eso.vse.cz/~zofm00/cv03/cheatsheet.html
https://eso.vse.cz/~zofm00/cv03/blog.html
https://eso.vse.cz/~zofm00/cv03/resume.html

**Comment by nvbach91** [comment]
```html

    <title>
        <h1>Strukturovaný životopis</h1>
    </title>
```
v title má být pouze text a ne další element
