### ISSUE TITLE
DÚ_chyby

### ISSUE THREAD

**Issue by lukyPinky** [nvbach91/4IZ268-2020-2021-ZS#4]
Dobrý den,
mohl bych se prosím zeptat na své chyby v DÚ. Validátorem mi to prošlo čistě, ale měl jsem !!!. 

Děkuji.

https://eso.vse.cz/~pinl01/cv03/index.html
https://eso.vse.cz/~pinl01/cv03/cheatsheet.html
https://eso.vse.cz/~pinl01/cv03/blog.html
https://eso.vse.cz/~pinl01/cv03/resume.html

**Comment by nvbach91** [comment]
- nemáte formátovaní kódu
- chybí ukončovací tag `</p>` v resume.html

**Comment by lukyPinky** [comment]
Díky.

 **Opraveno.**
