### ISSUE TITLE
DU_cv03... sinj04!!

### ISSUE THREAD

**Issue by BlazeCZ** [nvbach91/4IZ268-2020-2021-ZS#5]
Dobrý den, rád bych se pro jistotu poptal ohledně chyb. Měl jsem dva vykřičníky, ale přes validátor jak v VSC tak na webu mi to projde bez warningů, či errorů. Jediné na co jsem přišel je že mi chyběl u některých dokumentů formát. Může se jednat jen o toto?
Předem děkuji za odpověď.

https://eso.vse.cz/~sinj04/cv03/index.html
https://eso.vse.cz/~sinj04/cv03/cheatsheet.html
https://eso.vse.cz/~sinj04/cv03/blog.html
https://eso.vse.cz/~sinj04/cv03/resume.html

**Comment by nvbach91** [comment]
ano přesně tak, a jinak názvy atributů id, name a class pište v angličtině

**Comment by BlazeCZ** [comment]
Dobře, děkuji.
