### ISSUE TITLE
SP1: Použití externích JavaScript tříd

### ISSUE THREAD

**Issue by hawrancz99** [nvbach91/4IZ268-2020-2021-ZS#55]
Dobrý den,
Chtěl bych se zeptat, zda můžeme v rámci naší seminární práce SP1 použít i externí js třídy. Konkrétně bych chtěl použít toto:
https://inorganik.github.io/countUp.js/ a https://postmail.invotes.com/.

Děkuji

**Comment by nvbach91** [comment]
Dobrý den, pro SP1 nelze použít JavaScript, pro SP2 lze použít cokoliv.
