### ISSUE TITLE
Responzivní design SP1

### ISSUE THREAD

**Issue by jpodestat** [nvbach91/4IZ268-2020-2021-ZS#64]
Dobrý den,
v požadavcích na SP1 píšete : "web je zobrazitelný i při rozlišení 800x600, všechny důležité informace nad přehybem (tj. v celém tomto prostoru nebude jen fotka…)"
Znamená to tedy, že práce nemusí být přizpůsobena pro nižší rozlišení (např. mobily)., ale nejníž právě těch 800x600?

**Comment by nvbach91** [comment]
Ano, 800x600 je požadavkem, ale když budete dělat s přístupem mobile-first, tak proč nezačínat s 320x568 a postupně rozšiřovat až na 1920x1080. https://mediag.com/blog/popular-screen-resolutions-designing-for-all/
