### ISSUE TITLE
hw04-problem se zadanim

### ISSUE THREAD

**Issue by anetapls** [nvbach91/4IZ268-2020-2021-ZS#8]
Zdravím, v zadání je napsáno, že se máme řídit textem, jenže ten si někdy protiřečí v obrázkovém návrhu řešení ( blue bold text není v ukázce bold, capitalized je v ukázce uppercase atd.). Máme obrázkový návrh ignorovat a řídit se čistě textem?

**Comment by nvbach91** [comment]
Doporučuji se řídit textem a pak teprve to porovnat s obrázkem. Jinak dobré postřehy..
