### ISSUE TITLE
valm08-sp1

### ISSUE THREAD

**Issue by valm08** [nvbach91/4IZ268-2020-2021-ZS#86]
Dobrý den,
Vaše vyhodnocení SP1 je nejednoznačné.

nedostatky:

img width attribut - OK

html entity - jestli myslíte [tento seznam](https://dev.w3.org/html5/html-author/charref) a skutečnost, že používám © jako symbol, tak 1. nikde v požadavcích o tom nic není. 2. Proč je to problém? Funguje to. Validátor to nevidí jako problém.

web font - v požadavcích je vhodná volba fontu, ne používání webového fontu, který je v rozporu s požadavkem na rychlost. Pokud máme používat webový font, bylo by vhodné pozměnit požadavky na font.

optimalizace obrazku - všechny jpg a png obrázky jsou optimalizované. V případě Latitude.webp tak ten se zdá být optimalizovaný již Dellem a všechny svg jsou rovněž malé. Jediný případ, kde by šlo optimalizovat, je logo MS Office, ale i to má malou velikost. Můžete si to ověřit na příloze. Obsahuje jak originál, tak komprimovanou verzi.
[WebImg.zip](https://github.com/nvbach91/4IZ268-2020-2021-ZS/files/5573536/WebImg.zip)

spatne rozdelene sloupce - OK

spatna orientace v informacich - ???

dlouhy text na sirku stranky  - asi. Jestli myslíte šířku textu na hl. stránce a referenci, tak 150 znaků na řádku je trochu delší.

nevhodne koncipovana a nastylovana navigace - OK

nepouzivani slozek a index.html - nikde v požadavcích to nevidím, ale OK

nejasna identifikace webu na jednotlivych strankach - podle mě je velmi jasná - h1 i title identifikují stránku, kde jsem.

nevhodne prizpusobeni pro tisk - trochu „skřípe“, OK

web neni vubec esteticky navrzeny ani neni uzivatelsky privetity, poslechnete si prednasku ohledne navrhu webu, a nechte se inspirovat od nejakeho moderniho webu - není esteticky navržený, ale v uživatelské přívětivosti nevidím problém. Je to prostě jednoduchá stránka, kde se zobrazují boxy s textem a obrázky. Co je na tom uživatelsky nepřívětivé? Nanejvýš ta navigace.

Děkuji za objasnění.

**Comment by nvbach91** [comment]
- html entity se pouzivaji z duvodu lepsi kompatibility z pohledu kodovani souboru a interpretace obsahu, spravne byste mel pouzivat i `&quot;` apod.
- asi nechapete jednu vec, a to ucel semestralky neni jen o tom splnit vsechny kladene pozadavky, ty slouzi jen jako guideline k tomu abyste neudelali ty nejcastejsi chyby, pouzivani nejakeho web fontu nestoji skoro nic a pritom vas web posune o uroven vys z pohledu kvality, mimochodem font ktery pouzivate urcite neni vhodne zvoleny, takovy font se pouziva spiste pro typy webu jako blogy kde jsou nejake clanky npod.
- vsechny obrazky by se mely optimalizovat, bez vyjimky
- myslim ze nejsem jediny kdo ma problem s tim cist parametry tech produktu v paragrafech, vzdyt to mate skoro jako souvisly text, mohl jste tam udelat neco jako tabulkovy layout (bez `<table>`) se 2 slp., podivejte se treba na alzu nebo czc jak to tam maji udelane pro ty jejich produkty a zkuste to napodobit
- typograficky to neni spravne mit tolik znaku na jednom radku, doporucuje se 60 znaku, to je taky duvod proc na novinach jsou sloupce
- nechapu proc se navigace meni s kazdou strankou, navic aktivni polozka v navigaci neni zvyraznena
- myslim ze jsem to jasne rekl behem cv03 a cv04 proc je to lepsi takto mit
- zkuste na kazde strance pridat logo webu 
- a jaky pocit a zazitek z toho webu mate vy, resp. jak byste svou praci zhodnotil?

**Comment by valm08** [comment]
Oprava:
https://eso.vse.cz/~valm08/sp1/
https://eso.vse.cz/~valm08/sp1/pc/
https://eso.vse.cz/~valm08/sp1/sw/
https://eso.vse.cz/~valm08/sp1/acs/
https://eso.vse.cz/~valm08/sp1/ref/

https://eso.vse.cz/~valm08/sp1/assets/css/default.css

Změny: struktura složek, drobná změna tisku, komprese dalších obrázků (někdy s nulovou úsporou), úprava navigace, změna písma, logo, HTML struktura produktů, šířka řádků a řádkování, asi další věci.

Edit 1:HTML entity, img width,...

**Comment by nvbach91** [comment]
- myslim ze v importu fontu ma byt 700 misto 300, font-weight 700 je bold, coz pouzivate ale nemate naimportovany, naopak 300 nepouzivate ale mate naimportovany
- tu mriz tech produktu zkuste zarovnat na stred
- odkazy na externi web by se mely otevrit v nove zalozce
- nastylujte header, navigaci a footer tak aby byly jasne odlisitelne od hlavniho obsahu
- navigacni prvky zvetsete (kontejner) aby se na ne dalo snadneji klikat, pouzijte vhodnejsi styly pro navigaci - inspirujte se na nejakem jinem webu, pouzijte napr. nejaky efekt pri hoveru
- pro trademark take existuje html entita
- vhodnym zpusobem zvyraznete ceny produktu
- produkty nastylujte tak aby meli konzistentni vizualni strukturu
- nazvy parametru produktu a jejich hodnoty od sebe odliste, napr. zvyraznit parametr a informace dat do tabulky (bez pouziti `<table>`)
-

**Comment by valm08** [comment]
Já už si s tím nevím rady. Prostě mi za to dejte nějaké body, je mi celkem jedno kolik, a je to. _Neumím_ to opravit a nemám jenom tenhle předmět a nedává smysl obětovat zbytek kvůli jedné SP.

**Comment by nvbach91** [comment]
škoda, takový potenciál to mělo
