### ISSUE TITLE
Nefunkční odkazy

### ISSUE THREAD

**Issue by alexmalychu** [nvbach91/4IZ268-2020-2021-ZS#90]
Dobrý den.
Stále mi nefungují odkazy na mé webovky, i když jsou soubory nahrané na webu (teda aspoň mně se ve WinSCP zobrazují). Vyscreenoval jsem soubory ve WinSCP i odkazy. Mohl byste mi prosím poradit, co tam mám špatně, na co jsem zapomněl nebo prostě proč ty odkazy nefungují?

![Mala12+sp1 složky](https://user-images.githubusercontent.com/72271761/100134574-b5797d00-2e88-11eb-8519-32ae39bc069f.png)
![Nefunkční odkazy](https://user-images.githubusercontent.com/72271761/100134578-b6aaaa00-2e88-11eb-88da-5536d58284ec.png)
![Složka Home](https://user-images.githubusercontent.com/72271761/100134580-b7434080-2e88-11eb-962f-c463e4129475.png)

**Comment by nvbach91** [comment]
To je z toho duvodu ze jste to nahral do nespravneho adresare, ja to mam takhle:
![image](https://user-images.githubusercontent.com/20724910/100271286-867f0c00-2f59-11eb-9585-d02b2af21f4c.png)

tam se dostanete z domovskeho adresare (ikona domecek) pres public_html slozku

**Comment by alexmalychu** [comment]
Dobře, děkuju. Odkazy už mám funkční.
